import { actions_minus_can_minus_approve_minus_pull_minus_request_minus_reviews } from "./actions_minus_can_minus_approve_minus_pull_minus_request_minus_reviews";
import { actions_minus_default_minus_workflow_minus_permissions } from "./actions_minus_default_minus_workflow_minus_permissions";

export type actions_minus_get_minus_default_minus_workflow_minus_permissions = {
  default_workflow_permissions: actions_minus_default_minus_workflow_minus_permissions;
  can_approve_pull_request_reviews: actions_minus_can_minus_approve_minus_pull_minus_request_minus_reviews;
};
