import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import { IApiReposRulesetsRuleSuites } from "../../../../structures/IApiReposRulesetsRuleSuites";
import { rule_minus_suite } from "../../../../structures/rule_minus_suite";
import { rule_minus_suites } from "../../../../structures/rule_minus_suites";

/**
 * List repository rule suites.
 * Lists suites of rule evaluations at the repository level.
 * For more information, see "[Managing rulesets for a repository](https://docs.github.com/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/managing-rulesets-for-a-repository#viewing-insights-for-rulesets)."
 *
 * @tag repos
 * @path repos/:owner/:repo/rulesets/rule-suites
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getByOwnerAndRepo(
  connection: IConnection<getByOwnerAndRepo.Headers>,
  owner: string,
  repo: string,
): Promise<getByOwnerAndRepo.Output> {
  return !!connection.simulate
    ? getByOwnerAndRepo.simulate(connection, owner, repo)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getByOwnerAndRepo.METADATA,
          path: getByOwnerAndRepo.path(owner, repo),
          status: null,
        },
      );
}
export namespace getByOwnerAndRepo {
  export type Headers = IApiReposRulesetsRuleSuites.GetHeader;
  export type Output = rule_minus_suites;

  export const METADATA = {
    method: "GET",
    path: "/repos/:owner/:repo/rulesets/rule-suites",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (owner: string, repo: string) =>
    `/repos/${encodeURIComponent(owner ?? "null")}/${encodeURIComponent(repo ?? "null")}/rulesets/rule-suites`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): rule_minus_suites => typia.random<rule_minus_suites>(g);
  export const simulate = (
    connection: IConnection<getByOwnerAndRepo.Headers>,
    owner: string,
    repo: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: getByOwnerAndRepo.path(owner, repo),
      contentType: "application/json",
    });
    try {
      assert.param("owner")(() => typia.assert(owner));
      assert.param("repo")(() => typia.assert(repo));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
/**
 * Get a repository rule suite.
 * Gets information about a suite of rule evaluations from within a repository.
 * For more information, see "[Managing rulesets for a repository](https://docs.github.com/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/managing-rulesets-for-a-repository#viewing-insights-for-rulesets)."
 *
 * @tag repos
 * @path repos/:owner/:repo/rulesets/rule-suites/:rule_suite_id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getByOwnerAndRepoAndRule_suite_id(
  connection: IConnection<getByOwnerAndRepoAndRule_suite_id.Headers>,
  owner: string,
  repo: string,
  rule_suite_id: string,
): Promise<getByOwnerAndRepoAndRule_suite_id.Output> {
  return !!connection.simulate
    ? getByOwnerAndRepoAndRule_suite_id.simulate(
        connection,
        owner,
        repo,
        rule_suite_id,
      )
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getByOwnerAndRepoAndRule_suite_id.METADATA,
          path: getByOwnerAndRepoAndRule_suite_id.path(
            owner,
            repo,
            rule_suite_id,
          ),
          status: null,
        },
      );
}
export namespace getByOwnerAndRepoAndRule_suite_id {
  export type Headers = IApiReposRulesetsRuleSuites.GetHeader;
  export type Output = rule_minus_suite;

  export const METADATA = {
    method: "GET",
    path: "/repos/:owner/:repo/rulesets/rule-suites/:rule_suite_id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (owner: string, repo: string, rule_suite_id: string) =>
    `/repos/${encodeURIComponent(owner ?? "null")}/${encodeURIComponent(repo ?? "null")}/rulesets/rule-suites/${encodeURIComponent(rule_suite_id ?? "null")}`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): rule_minus_suite => typia.random<rule_minus_suite>(g);
  export const simulate = (
    connection: IConnection<getByOwnerAndRepoAndRule_suite_id.Headers>,
    owner: string,
    repo: string,
    rule_suite_id: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: getByOwnerAndRepoAndRule_suite_id.path(owner, repo, rule_suite_id),
      contentType: "application/json",
    });
    try {
      assert.param("owner")(() => typia.assert(owner));
      assert.param("repo")(() => typia.assert(repo));
      assert.param("rule_suite_id")(() => typia.assert(rule_suite_id));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
