import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IApiEnterprisesDependabotAlerts } from "../../../../structures/IApiEnterprisesDependabotAlerts";
import { dependabot_minus_alert_minus_with_minus_repository } from "../../../../structures/dependabot_minus_alert_minus_with_minus_repository";
/**
 * List Dependabot alerts for an enterprise.
 * Lists Dependabot alerts for repositories that are owned by the specified enterprise.
 *
 * The authenticated user must be a member of the enterprise to use this endpoint.
 *
 * Alerts are only returned for organizations in the enterprise for which you are an organization owner or a security manager. For more information about security managers, see "[Managing security managers in your organization](https://docs.github.com/organizations/managing-peoples-access-to-your-organization-with-roles/managing-security-managers-in-your-organization)."
 *
 * OAuth app tokens and personal access tokens (classic) need the `repo` or `security_events` scope to use this endpoint.
 *
 * @tag dependabot
 * @path enterprises/:enterprise/dependabot/alerts
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getByEnterprise(
  connection: IConnection<getByEnterprise.Headers>,
  enterprise: string,
): Promise<getByEnterprise.Output> {
  return !!connection.simulate
    ? getByEnterprise.simulate(connection, enterprise)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getByEnterprise.METADATA,
          path: getByEnterprise.path(enterprise),
          status: null,
        },
      );
}
export namespace getByEnterprise {
  export type Headers = IApiEnterprisesDependabotAlerts.GetHeader;
  export type Output = dependabot_minus_alert_minus_with_minus_repository[];

  export const METADATA = {
    method: "GET",
    path: "/enterprises/:enterprise/dependabot/alerts",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (enterprise: string) =>
    `/enterprises/${encodeURIComponent(enterprise ?? "null")}/dependabot/alerts`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): dependabot_minus_alert_minus_with_minus_repository[] =>
    typia.random<dependabot_minus_alert_minus_with_minus_repository[]>(g);
  export const simulate = (
    connection: IConnection<getByEnterprise.Headers>,
    enterprise: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: getByEnterprise.path(enterprise),
      contentType: "application/json",
    });
    try {
      assert.param("enterprise")(() => typia.assert(enterprise));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
