import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IApiReposCodeScanningAlerts } from "../../../../structures/IApiReposCodeScanningAlerts";
import { code_minus_scanning_minus_alert_minus_items } from "../../../../structures/code_minus_scanning_minus_alert_minus_items";
import { code_minus_scanning_minus_alert } from "../../../../structures/code_minus_scanning_minus_alert";
import { body } from "../../../../structures/body";
export * as instances from "./instances";
/**
 * List code scanning alerts for a repository.
 * Lists code scanning alerts.
 *
 * The response includes a `most_recent_instance` object.
 * This provides details of the most recent instance of this alert
 * for the default branch (or for the specified Git reference if you used `ref` in the request).
 *
 * OAuth app tokens and personal access tokens (classic) need the `security_events` scope to use this endpoint with private or public repositories, or the `public_repo` scope to use this endpoint with only public repositories.
 *
 * @tag code-scanning
 * @path repos/:owner/:repo/code-scanning/alerts
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getByOwnerAndRepo(
  connection: IConnection<getByOwnerAndRepo.Headers>,
  owner: string,
  repo: string,
  query: getByOwnerAndRepo.Query,
): Promise<getByOwnerAndRepo.Output> {
  return !!connection.simulate
    ? getByOwnerAndRepo.simulate(connection, owner, repo, query)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getByOwnerAndRepo.METADATA,
          path: getByOwnerAndRepo.path(owner, repo, query),
          status: null,
        },
      );
}
export namespace getByOwnerAndRepo {
  export type Headers = IApiReposCodeScanningAlerts.GetHeader;
  export type Query = IApiReposCodeScanningAlerts.GetQuery;
  export type Output = code_minus_scanning_minus_alert_minus_items[];

  export const METADATA = {
    method: "GET",
    path: "/repos/:owner/:repo/code-scanning/alerts",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (
    owner: string,
    repo: string,
    query: getByOwnerAndRepo.Query,
  ) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = `/repos/${encodeURIComponent(owner ?? "null")}/${encodeURIComponent(repo ?? "null")}/code-scanning/alerts`;
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): code_minus_scanning_minus_alert_minus_items[] =>
    typia.random<code_minus_scanning_minus_alert_minus_items[]>(g);
  export const simulate = (
    connection: IConnection<getByOwnerAndRepo.Headers>,
    owner: string,
    repo: string,
    query: getByOwnerAndRepo.Query,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: getByOwnerAndRepo.path(owner, repo, query),
      contentType: "application/json",
    });
    try {
      assert.param("owner")(() => typia.assert(owner));
      assert.param("repo")(() => typia.assert(repo));
      assert.query(() => typia.assert(query));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
/**
 * Get a code scanning alert.
 * Gets a single code scanning alert.
 *
 * OAuth app tokens and personal access tokens (classic) need the `security_events` scope to use this endpoint with private or public repositories, or the `public_repo` scope to use this endpoint with only public repositories.
 *
 * @tag code-scanning
 * @path repos/:owner/:repo/code-scanning/alerts/:alert_number
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getByOwnerAndRepoAndAlert_number(
  connection: IConnection<getByOwnerAndRepoAndAlert_number.Headers>,
  owner: string,
  repo: string,
  alert_number: string,
): Promise<getByOwnerAndRepoAndAlert_number.Output> {
  return !!connection.simulate
    ? getByOwnerAndRepoAndAlert_number.simulate(
        connection,
        owner,
        repo,
        alert_number,
      )
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getByOwnerAndRepoAndAlert_number.METADATA,
          path: getByOwnerAndRepoAndAlert_number.path(
            owner,
            repo,
            alert_number,
          ),
          status: null,
        },
      );
}
export namespace getByOwnerAndRepoAndAlert_number {
  export type Headers = IApiReposCodeScanningAlerts.GetHeader;
  export type Output = code_minus_scanning_minus_alert;

  export const METADATA = {
    method: "GET",
    path: "/repos/:owner/:repo/code-scanning/alerts/:alert_number",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (owner: string, repo: string, alert_number: string) =>
    `/repos/${encodeURIComponent(owner ?? "null")}/${encodeURIComponent(repo ?? "null")}/code-scanning/alerts/${encodeURIComponent(alert_number ?? "null")}`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): code_minus_scanning_minus_alert =>
    typia.random<code_minus_scanning_minus_alert>(g);
  export const simulate = (
    connection: IConnection<getByOwnerAndRepoAndAlert_number.Headers>,
    owner: string,
    repo: string,
    alert_number: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: getByOwnerAndRepoAndAlert_number.path(owner, repo, alert_number),
      contentType: "application/json",
    });
    try {
      assert.param("owner")(() => typia.assert(owner));
      assert.param("repo")(() => typia.assert(repo));
      assert.param("alert_number")(() => typia.assert(alert_number));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
/**
 * Update a code scanning alert.
 * Updates the status of a single code scanning alert.
 * OAuth app tokens and personal access tokens (classic) need the `security_events` scope to use this endpoint with private or public repositories, or the `public_repo` scope to use this endpoint with only public repositories.
 *
 * @tag code-scanning
 * @path repos/:owner/:repo/code-scanning/alerts/:alert_number
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function patchByOwnerAndRepoAndAlert_number(
  connection: IConnection<patchByOwnerAndRepoAndAlert_number.Headers>,
  owner: string,
  repo: string,
  alert_number: string,
  body: patchByOwnerAndRepoAndAlert_number.Input,
): Promise<patchByOwnerAndRepoAndAlert_number.Output> {
  return !!connection.simulate
    ? patchByOwnerAndRepoAndAlert_number.simulate(
        connection,
        owner,
        repo,
        alert_number,
        body,
      )
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...patchByOwnerAndRepoAndAlert_number.METADATA,
          path: patchByOwnerAndRepoAndAlert_number.path(
            owner,
            repo,
            alert_number,
          ),
          status: null,
        },
        body,
      );
}
export namespace patchByOwnerAndRepoAndAlert_number {
  export type Headers = IApiReposCodeScanningAlerts.PatchHeader;
  export type Input = body;
  export type Output = code_minus_scanning_minus_alert;

  export const METADATA = {
    method: "PATCH",
    path: "/repos/:owner/:repo/code-scanning/alerts/:alert_number",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (owner: string, repo: string, alert_number: string) =>
    `/repos/${encodeURIComponent(owner ?? "null")}/${encodeURIComponent(repo ?? "null")}/code-scanning/alerts/${encodeURIComponent(alert_number ?? "null")}`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): code_minus_scanning_minus_alert =>
    typia.random<code_minus_scanning_minus_alert>(g);
  export const simulate = (
    connection: IConnection<patchByOwnerAndRepoAndAlert_number.Headers>,
    owner: string,
    repo: string,
    alert_number: string,
    body: patchByOwnerAndRepoAndAlert_number.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: patchByOwnerAndRepoAndAlert_number.path(owner, repo, alert_number),
      contentType: "application/json",
    });
    try {
      assert.param("owner")(() => typia.assert(owner));
      assert.param("repo")(() => typia.assert(repo));
      assert.param("alert_number")(() => typia.assert(alert_number));
      assert.body(() => typia.assert(body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
