import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IApiReposEnvironmentsSecrets } from "../../../../structures/IApiReposEnvironmentsSecrets";
import { response } from "../../../../structures/response";
import { actions_minus_secret } from "../../../../structures/actions_minus_secret";
import { body } from "../../../../structures/body";
import { empty_minus_object } from "../../../../structures/empty_minus_object";
export * as public_key from "./public_key";
/**
 * List environment secrets.
 * Lists all secrets available in an environment without revealing their
 * encrypted values.
 *
 * Authenticated users must have collaborator access to a repository to create, update, or read secrets.
 *
 * OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
 *
 * @tag actions
 * @path repos/:owner/:repo/environments/:environment_name/secrets
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getByOwnerAndRepoAndEnvironment_name(
  connection: IConnection<getByOwnerAndRepoAndEnvironment_name.Headers>,
  owner: string,
  repo: string,
  environment_name: string,
): Promise<getByOwnerAndRepoAndEnvironment_name.Output> {
  return !!connection.simulate
    ? getByOwnerAndRepoAndEnvironment_name.simulate(
        connection,
        owner,
        repo,
        environment_name,
      )
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getByOwnerAndRepoAndEnvironment_name.METADATA,
          path: getByOwnerAndRepoAndEnvironment_name.path(
            owner,
            repo,
            environment_name,
          ),
          status: null,
        },
      );
}
export namespace getByOwnerAndRepoAndEnvironment_name {
  export type Headers = IApiReposEnvironmentsSecrets.GetHeader;
  export type Output = response;

  export const METADATA = {
    method: "GET",
    path: "/repos/:owner/:repo/environments/:environment_name/secrets",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (owner: string, repo: string, environment_name: string) =>
    `/repos/${encodeURIComponent(owner ?? "null")}/${encodeURIComponent(repo ?? "null")}/environments/${encodeURIComponent(environment_name ?? "null")}/secrets`;
  export const random = (g?: Partial<typia.IRandomGenerator>): response =>
    typia.random<response>(g);
  export const simulate = (
    connection: IConnection<getByOwnerAndRepoAndEnvironment_name.Headers>,
    owner: string,
    repo: string,
    environment_name: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: getByOwnerAndRepoAndEnvironment_name.path(
        owner,
        repo,
        environment_name,
      ),
      contentType: "application/json",
    });
    try {
      assert.param("owner")(() => typia.assert(owner));
      assert.param("repo")(() => typia.assert(repo));
      assert.param("environment_name")(() => typia.assert(environment_name));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
/**
 * Get an environment secret.
 * Gets a single environment secret without revealing its encrypted value.
 *
 * Authenticated users must have collaborator access to a repository to create, update, or read secrets.
 *
 * OAuth tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
 *
 * @tag actions
 * @path repos/:owner/:repo/environments/:environment_name/secrets/:secret_name
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getByOwnerAndRepoAndEnvironment_nameAndSecret_name(
  connection: IConnection<getByOwnerAndRepoAndEnvironment_nameAndSecret_name.Headers>,
  owner: string,
  repo: string,
  environment_name: string,
  secret_name: string,
): Promise<getByOwnerAndRepoAndEnvironment_nameAndSecret_name.Output> {
  return !!connection.simulate
    ? getByOwnerAndRepoAndEnvironment_nameAndSecret_name.simulate(
        connection,
        owner,
        repo,
        environment_name,
        secret_name,
      )
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getByOwnerAndRepoAndEnvironment_nameAndSecret_name.METADATA,
          path: getByOwnerAndRepoAndEnvironment_nameAndSecret_name.path(
            owner,
            repo,
            environment_name,
            secret_name,
          ),
          status: null,
        },
      );
}
export namespace getByOwnerAndRepoAndEnvironment_nameAndSecret_name {
  export type Headers = IApiReposEnvironmentsSecrets.GetHeader;
  export type Output = actions_minus_secret;

  export const METADATA = {
    method: "GET",
    path: "/repos/:owner/:repo/environments/:environment_name/secrets/:secret_name",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (
    owner: string,
    repo: string,
    environment_name: string,
    secret_name: string,
  ) =>
    `/repos/${encodeURIComponent(owner ?? "null")}/${encodeURIComponent(repo ?? "null")}/environments/${encodeURIComponent(environment_name ?? "null")}/secrets/${encodeURIComponent(secret_name ?? "null")}`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): actions_minus_secret => typia.random<actions_minus_secret>(g);
  export const simulate = (
    connection: IConnection<getByOwnerAndRepoAndEnvironment_nameAndSecret_name.Headers>,
    owner: string,
    repo: string,
    environment_name: string,
    secret_name: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: getByOwnerAndRepoAndEnvironment_nameAndSecret_name.path(
        owner,
        repo,
        environment_name,
        secret_name,
      ),
      contentType: "application/json",
    });
    try {
      assert.param("owner")(() => typia.assert(owner));
      assert.param("repo")(() => typia.assert(repo));
      assert.param("environment_name")(() => typia.assert(environment_name));
      assert.param("secret_name")(() => typia.assert(secret_name));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
/**
 * Create or update an environment secret.
 * Creates or updates an environment secret with an encrypted value. Encrypt your secret using
 * [LibSodium](https://libsodium.gitbook.io/doc/bindings_for_other_languages). For more information, see "[Encrypting secrets for the REST API](https://docs.github.com/rest/guides/encrypting-secrets-for-the-rest-api)."
 *
 * Authenticated users must have collaborator access to a repository to create, update, or read secrets.
 *
 * OAuth tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
 *
 * @tag actions
 * @path repos/:owner/:repo/environments/:environment_name/secrets/:secret_name
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function putByOwnerAndRepoAndEnvironment_nameAndSecret_name(
  connection: IConnection<putByOwnerAndRepoAndEnvironment_nameAndSecret_name.Headers>,
  owner: string,
  repo: string,
  environment_name: string,
  secret_name: string,
  body: putByOwnerAndRepoAndEnvironment_nameAndSecret_name.Input,
): Promise<putByOwnerAndRepoAndEnvironment_nameAndSecret_name.Output> {
  return !!connection.simulate
    ? putByOwnerAndRepoAndEnvironment_nameAndSecret_name.simulate(
        connection,
        owner,
        repo,
        environment_name,
        secret_name,
        body,
      )
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...putByOwnerAndRepoAndEnvironment_nameAndSecret_name.METADATA,
          path: putByOwnerAndRepoAndEnvironment_nameAndSecret_name.path(
            owner,
            repo,
            environment_name,
            secret_name,
          ),
          status: null,
        },
        body,
      );
}
export namespace putByOwnerAndRepoAndEnvironment_nameAndSecret_name {
  export type Headers = IApiReposEnvironmentsSecrets.PutHeader;
  export type Input = body;
  export type Output = empty_minus_object;

  export const METADATA = {
    method: "PUT",
    path: "/repos/:owner/:repo/environments/:environment_name/secrets/:secret_name",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (
    owner: string,
    repo: string,
    environment_name: string,
    secret_name: string,
  ) =>
    `/repos/${encodeURIComponent(owner ?? "null")}/${encodeURIComponent(repo ?? "null")}/environments/${encodeURIComponent(environment_name ?? "null")}/secrets/${encodeURIComponent(secret_name ?? "null")}`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): empty_minus_object => typia.random<empty_minus_object>(g);
  export const simulate = (
    connection: IConnection<putByOwnerAndRepoAndEnvironment_nameAndSecret_name.Headers>,
    owner: string,
    repo: string,
    environment_name: string,
    secret_name: string,
    body: putByOwnerAndRepoAndEnvironment_nameAndSecret_name.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: putByOwnerAndRepoAndEnvironment_nameAndSecret_name.path(
        owner,
        repo,
        environment_name,
        secret_name,
      ),
      contentType: "application/json",
    });
    try {
      assert.param("owner")(() => typia.assert(owner));
      assert.param("repo")(() => typia.assert(repo));
      assert.param("environment_name")(() => typia.assert(environment_name));
      assert.param("secret_name")(() => typia.assert(secret_name));
      assert.body(() => typia.assert(body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
/**
 * Delete an environment secret.
 * Deletes a secret in an environment using the secret name.
 *
 * Authenticated users must have collaborator access to a repository to create, update, or read secrets.
 *
 * OAuth tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
 *
 * @tag actions
 * @path repos/:owner/:repo/environments/:environment_name/secrets/:secret_name
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function eraseByOwnerAndRepoAndEnvironment_nameAndSecret_name(
  connection: IConnection<eraseByOwnerAndRepoAndEnvironment_nameAndSecret_name.Headers>,
  owner: string,
  repo: string,
  environment_name: string,
  secret_name: string,
): Promise<void> {
  return !!connection.simulate
    ? eraseByOwnerAndRepoAndEnvironment_nameAndSecret_name.simulate(
        connection,
        owner,
        repo,
        environment_name,
        secret_name,
      )
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...eraseByOwnerAndRepoAndEnvironment_nameAndSecret_name.METADATA,
          path: eraseByOwnerAndRepoAndEnvironment_nameAndSecret_name.path(
            owner,
            repo,
            environment_name,
            secret_name,
          ),
          status: null,
        },
      );
}
export namespace eraseByOwnerAndRepoAndEnvironment_nameAndSecret_name {
  export type Headers = IApiReposEnvironmentsSecrets.DeleteHeader;

  export const METADATA = {
    method: "DELETE",
    path: "/repos/:owner/:repo/environments/:environment_name/secrets/:secret_name",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (
    owner: string,
    repo: string,
    environment_name: string,
    secret_name: string,
  ) =>
    `/repos/${encodeURIComponent(owner ?? "null")}/${encodeURIComponent(repo ?? "null")}/environments/${encodeURIComponent(environment_name ?? "null")}/secrets/${encodeURIComponent(secret_name ?? "null")}`;
  export const random = (g?: Partial<typia.IRandomGenerator>): void =>
    typia.random<void>(g);
  export const simulate = (
    connection: IConnection<eraseByOwnerAndRepoAndEnvironment_nameAndSecret_name.Headers>,
    owner: string,
    repo: string,
    environment_name: string,
    secret_name: string,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: eraseByOwnerAndRepoAndEnvironment_nameAndSecret_name.path(
        owner,
        repo,
        environment_name,
        secret_name,
      ),
      contentType: "application/json",
    });
    try {
      assert.param("owner")(() => typia.assert(owner));
      assert.param("repo")(() => typia.assert(repo));
      assert.param("environment_name")(() => typia.assert(environment_name));
      assert.param("secret_name")(() => typia.assert(secret_name));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
