import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IApiUserKeys } from "../../../structures/IApiUserKeys";
import { key } from "../../../structures/key";
import { body } from "../../../structures/body";
/**
 * List public SSH keys for the authenticated user.
 * Lists the public SSH keys for the authenticated user's GitHub account.
 *
 * OAuth app tokens and personal access tokens (classic) need the `read:public_key` scope to use this endpoint.
 *
 * @tag users
 * @path user/keys
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function get(
  connection: IConnection<get.Headers>,
): Promise<get.Output> {
  return !!connection.simulate
    ? get.simulate(connection)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...get.METADATA,
          path: get.path(),
          status: null,
        },
      );
}
export namespace get {
  export type Headers = IApiUserKeys.GetHeader;
  export type Output = key[];

  export const METADATA = {
    method: "GET",
    path: "/user/keys",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/user/keys";
  export const random = (g?: Partial<typia.IRandomGenerator>): key[] =>
    typia.random<key[]>(g);
  export const simulate = (connection: IConnection<get.Headers>): Output => {
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
/**
 * Create a public SSH key for the authenticated user.
 * Adds a public SSH key to the authenticated user's GitHub account.
 *
 * OAuth app tokens and personal access tokens (classic) need the `write:gpg_key` scope to use this endpoint.
 *
 * @tag users
 * @path user/keys
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function post(
  connection: IConnection,
  body: post.Input,
): Promise<post.Output> {
  return !!connection.simulate
    ? post.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...post.METADATA,
          path: post.path(),
          status: null,
        },
        body,
      );
}
export namespace post {
  export type Input = body;
  export type Output = key;

  export const METADATA = {
    method: "POST",
    path: "/user/keys",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/user/keys";
  export const random = (g?: Partial<typia.IRandomGenerator>): key =>
    typia.random<key>(g);
  export const simulate = (
    connection: IConnection,
    body: post.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: post.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
/**
 * Get a public SSH key for the authenticated user.
 * View extended details for a single public SSH key.
 *
 * OAuth app tokens and personal access tokens (classic) need the `read:public_key` scope to use this endpoint.
 *
 * @tag users
 * @path user/keys/:key_id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getByKey_id(
  connection: IConnection<getByKey_id.Headers>,
  key_id: string,
): Promise<getByKey_id.Output> {
  return !!connection.simulate
    ? getByKey_id.simulate(connection, key_id)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getByKey_id.METADATA,
          path: getByKey_id.path(key_id),
          status: null,
        },
      );
}
export namespace getByKey_id {
  export type Headers = IApiUserKeys.GetHeader;
  export type Output = key;

  export const METADATA = {
    method: "GET",
    path: "/user/keys/:key_id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (key_id: string) =>
    `/user/keys/${encodeURIComponent(key_id ?? "null")}`;
  export const random = (g?: Partial<typia.IRandomGenerator>): key =>
    typia.random<key>(g);
  export const simulate = (
    connection: IConnection<getByKey_id.Headers>,
    key_id: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: getByKey_id.path(key_id),
      contentType: "application/json",
    });
    try {
      assert.param("key_id")(() => typia.assert(key_id));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
/**
 * Delete a public SSH key for the authenticated user.
 * Removes a public SSH key from the authenticated user's GitHub account.
 *
 * OAuth app tokens and personal access tokens (classic) need the `admin:public_key` scope to use this endpoint.
 *
 * @tag users
 * @path user/keys/:key_id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function eraseByKey_id(
  connection: IConnection<eraseByKey_id.Headers>,
  key_id: string,
): Promise<void> {
  return !!connection.simulate
    ? eraseByKey_id.simulate(connection, key_id)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...eraseByKey_id.METADATA,
          path: eraseByKey_id.path(key_id),
          status: null,
        },
      );
}
export namespace eraseByKey_id {
  export type Headers = IApiUserKeys.DeleteHeader;

  export const METADATA = {
    method: "DELETE",
    path: "/user/keys/:key_id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (key_id: string) =>
    `/user/keys/${encodeURIComponent(key_id ?? "null")}`;
  export const random = (g?: Partial<typia.IRandomGenerator>): void =>
    typia.random<void>(g);
  export const simulate = (
    connection: IConnection<eraseByKey_id.Headers>,
    key_id: string,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: eraseByKey_id.path(key_id),
      contentType: "application/json",
    });
    try {
      assert.param("key_id")(() => typia.assert(key_id));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
