import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IApiGistsCommits } from "../../../structures/IApiGistsCommits";
import { gist_minus_commit } from "../../../structures/gist_minus_commit";
/**
 * @tag gists
 * @path gists/:gist_id/commits
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getByGist_id(
  connection: IConnection<getByGist_id.Headers>,
  gist_id: string,
): Promise<getByGist_id.Output> {
  return !!connection.simulate
    ? getByGist_id.simulate(connection, gist_id)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getByGist_id.METADATA,
          path: getByGist_id.path(gist_id),
          status: null,
        },
      );
}
export namespace getByGist_id {
  export type Headers = IApiGistsCommits.GetHeader;
  export type Output = gist_minus_commit[];

  export const METADATA = {
    method: "GET",
    path: "/gists/:gist_id/commits",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (gist_id: string) =>
    `/gists/${encodeURIComponent(gist_id ?? "null")}/commits`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): gist_minus_commit[] => typia.random<gist_minus_commit[]>(g);
  export const simulate = (
    connection: IConnection<getByGist_id.Headers>,
    gist_id: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: getByGist_id.path(gist_id),
      contentType: "application/json",
    });
    try {
      assert.param("gist_id")(() => typia.assert(gist_id));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
