import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IApiReposCheckSuitesPreferences } from "../../../../structures/IApiReposCheckSuitesPreferences";
import { body } from "../../../../structures/body";
import { check_minus_suite_minus_preference } from "../../../../structures/check_minus_suite_minus_preference";
/**
 * Update repository preferences for check suites.
 * Changes the default automatic flow when creating check suites. By default, a check suite is automatically created each time code is pushed to a repository. When you disable the automatic creation of check suites, you can manually [Create a check suite](https://docs.github.com/rest/checks/suites#create-a-check-suite).
 * You must have admin permissions in the repository to set preferences for check suites.
 *
 * @tag checks
 * @path repos/:owner/:repo/check-suites/preferences
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function patchByOwnerAndRepo(
  connection: IConnection<patchByOwnerAndRepo.Headers>,
  owner: string,
  repo: string,
  body: patchByOwnerAndRepo.Input,
): Promise<patchByOwnerAndRepo.Output> {
  return !!connection.simulate
    ? patchByOwnerAndRepo.simulate(connection, owner, repo, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...patchByOwnerAndRepo.METADATA,
          path: patchByOwnerAndRepo.path(owner, repo),
          status: null,
        },
        body,
      );
}
export namespace patchByOwnerAndRepo {
  export type Headers = IApiReposCheckSuitesPreferences.PatchHeader;
  export type Input = body;
  export type Output = check_minus_suite_minus_preference;

  export const METADATA = {
    method: "PATCH",
    path: "/repos/:owner/:repo/check-suites/preferences",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (owner: string, repo: string) =>
    `/repos/${encodeURIComponent(owner ?? "null")}/${encodeURIComponent(repo ?? "null")}/check-suites/preferences`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): check_minus_suite_minus_preference =>
    typia.random<check_minus_suite_minus_preference>(g);
  export const simulate = (
    connection: IConnection<patchByOwnerAndRepo.Headers>,
    owner: string,
    repo: string,
    body: patchByOwnerAndRepo.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: patchByOwnerAndRepo.path(owner, repo),
      contentType: "application/json",
    });
    try {
      assert.param("owner")(() => typia.assert(owner));
      assert.param("repo")(() => typia.assert(repo));
      assert.body(() => typia.assert(body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
