import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import { IApiOrgsActionsCacheUsage } from "../../../../../structures/IApiOrgsActionsCacheUsage";
import { actions_minus_cache_minus_usage_minus_org_minus_enterprise } from "../../../../../structures/actions_minus_cache_minus_usage_minus_org_minus_enterprise";

/**
 * Get GitHub Actions cache usage for an organization.
 * Gets the total GitHub Actions cache usage for an organization.
 * The data fetched using this API is refreshed approximately every 5 minutes, so values returned from this endpoint may take at least 5 minutes to get updated.
 *
 * OAuth tokens and personal access tokens (classic) need the `read:org` scope to use this endpoint.
 *
 * @tag actions
 * @path orgs/:org/actions/cache/usage
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getByOrg(
  connection: IConnection<getByOrg.Headers>,
  org: string,
): Promise<getByOrg.Output> {
  return !!connection.simulate
    ? getByOrg.simulate(connection, org)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getByOrg.METADATA,
          path: getByOrg.path(org),
          status: null,
        },
      );
}
export namespace getByOrg {
  export type Headers = IApiOrgsActionsCacheUsage.GetHeader;
  export type Output =
    actions_minus_cache_minus_usage_minus_org_minus_enterprise;

  export const METADATA = {
    method: "GET",
    path: "/orgs/:org/actions/cache/usage",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (org: string) =>
    `/orgs/${encodeURIComponent(org ?? "null")}/actions/cache/usage`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): actions_minus_cache_minus_usage_minus_org_minus_enterprise =>
    typia.random<actions_minus_cache_minus_usage_minus_org_minus_enterprise>(g);
  export const simulate = (
    connection: IConnection<getByOrg.Headers>,
    org: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: getByOrg.path(org),
      contentType: "application/json",
    });
    try {
      assert.param("org")(() => typia.assert(org));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
