import { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import { IApiUserTeams } from "../../../structures/IApiUserTeams";
import { team_minus_full } from "../../../structures/team_minus_full";

/**
 * List teams for the authenticated user.
 * List all of the teams across all of the organizations to which the authenticated
 * user belongs.
 *
 * OAuth app tokens and personal access tokens (classic) need the `user`, `repo`, or `read:org` scope to use this endpoint.
 *
 * When using a fine-grained personal access token, the resource owner of the token must be a single organization, and the response will only include the teams from that organization.
 *
 * @tag teams
 * @path user/teams
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function get(
  connection: IConnection<get.Headers>,
): Promise<get.Output> {
  return !!connection.simulate
    ? get.simulate(connection)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...get.METADATA,
          path: get.path(),
          status: null,
        },
      );
}
export namespace get {
  export type Headers = IApiUserTeams.GetHeader;
  export type Output = team_minus_full[];

  export const METADATA = {
    method: "GET",
    path: "/user/teams",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/user/teams";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): team_minus_full[] => typia.random<team_minus_full[]>(g);
  export const simulate = (connection: IConnection<get.Headers>): Output => {
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
