import { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import { IApiAppInstallationRequests } from "../../../structures/IApiAppInstallationRequests";
import { integration_minus_installation_minus_request } from "../../../structures/integration_minus_installation_minus_request";
/**
 * List installation requests for the authenticated app.
 * Lists all the pending installation requests for the authenticated GitHub App.
 *
 * @tag apps
 * @path app/installation-requests
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function get(
  connection: IConnection<get.Headers>,
): Promise<get.Output> {
  return !!connection.simulate
    ? get.simulate(connection)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...get.METADATA,
          path: get.path(),
          status: null,
        },
      );
}
export namespace get {
  export type Headers = IApiAppInstallationRequests.GetHeader;
  export type Output = integration_minus_installation_minus_request[];

  export const METADATA = {
    method: "GET",
    path: "/app/installation-requests",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/app/installation-requests";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): integration_minus_installation_minus_request[] =>
    typia.random<integration_minus_installation_minus_request[]>(g);
  export const simulate = (connection: IConnection<get.Headers>): Output => {
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
