import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import { IApiReposCheckSuitesRerequest } from "../../../../structures/IApiReposCheckSuitesRerequest";
import { empty_minus_object } from "../../../../structures/empty_minus_object";

/**
 * Rerequest a check suite.
 * Triggers GitHub to rerequest an existing check suite, without pushing new code to a repository. This endpoint will trigger the [`check_suite` webhook](https://docs.github.com/webhooks/event-payloads/#check_suite) event with the action `rerequested`. When a check suite is `rerequested`, its `status` is reset to `queued` and the `conclusion` is cleared.
 *
 * OAuth apps and personal access tokens (classic) cannot use this endpoint.
 *
 * @tag checks
 * @path repos/:owner/:repo/check-suites/:check_suite_id/rerequest
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function postByOwnerAndRepoAndCheck_suite_id(
  connection: IConnection<postByOwnerAndRepoAndCheck_suite_id.Headers>,
  owner: string,
  repo: string,
  check_suite_id: string,
): Promise<postByOwnerAndRepoAndCheck_suite_id.Output> {
  return !!connection.simulate
    ? postByOwnerAndRepoAndCheck_suite_id.simulate(
        connection,
        owner,
        repo,
        check_suite_id,
      )
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...postByOwnerAndRepoAndCheck_suite_id.METADATA,
          path: postByOwnerAndRepoAndCheck_suite_id.path(
            owner,
            repo,
            check_suite_id,
          ),
          status: null,
        },
      );
}
export namespace postByOwnerAndRepoAndCheck_suite_id {
  export type Headers = IApiReposCheckSuitesRerequest.PostHeader;
  export type Output = empty_minus_object;

  export const METADATA = {
    method: "POST",
    path: "/repos/:owner/:repo/check-suites/:check_suite_id/rerequest",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (owner: string, repo: string, check_suite_id: string) =>
    `/repos/${encodeURIComponent(owner ?? "null")}/${encodeURIComponent(repo ?? "null")}/check-suites/${encodeURIComponent(check_suite_id ?? "null")}/rerequest`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): empty_minus_object => typia.random<empty_minus_object>(g);
  export const simulate = (
    connection: IConnection<postByOwnerAndRepoAndCheck_suite_id.Headers>,
    owner: string,
    repo: string,
    check_suite_id: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: postByOwnerAndRepoAndCheck_suite_id.path(
        owner,
        repo,
        check_suite_id,
      ),
      contentType: "application/json",
    });
    try {
      assert.param("owner")(() => typia.assert(owner));
      assert.param("repo")(() => typia.assert(repo));
      assert.param("check_suite_id")(() => typia.assert(check_suite_id));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
