import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IApiReposStatuses } from "../../../structures/IApiReposStatuses";
import { body } from "../../../structures/body";
import { status } from "../../../structures/status";
/**
 * Create a commit status.
 * Users with push access in a repository can create commit statuses for a given SHA.
 *
 * Note: there is a limit of 1000 statuses per `sha` and `context` within a repository. Attempts to create more than 1000 statuses will result in a validation error.
 *
 * @tag repos
 * @path repos/:owner/:repo/statuses/:sha
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function postByOwnerAndRepoAndSha(
  connection: IConnection<postByOwnerAndRepoAndSha.Headers>,
  owner: string,
  repo: string,
  sha: string,
  body: postByOwnerAndRepoAndSha.Input,
): Promise<postByOwnerAndRepoAndSha.Output> {
  return !!connection.simulate
    ? postByOwnerAndRepoAndSha.simulate(connection, owner, repo, sha, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...postByOwnerAndRepoAndSha.METADATA,
          path: postByOwnerAndRepoAndSha.path(owner, repo, sha),
          status: null,
        },
        body,
      );
}
export namespace postByOwnerAndRepoAndSha {
  export type Headers = IApiReposStatuses.PostHeader;
  export type Input = body;
  export type Output = status;

  export const METADATA = {
    method: "POST",
    path: "/repos/:owner/:repo/statuses/:sha",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (owner: string, repo: string, sha: string) =>
    `/repos/${encodeURIComponent(owner ?? "null")}/${encodeURIComponent(repo ?? "null")}/statuses/${encodeURIComponent(sha ?? "null")}`;
  export const random = (g?: Partial<typia.IRandomGenerator>): status =>
    typia.random<status>(g);
  export const simulate = (
    connection: IConnection<postByOwnerAndRepoAndSha.Headers>,
    owner: string,
    repo: string,
    sha: string,
    body: postByOwnerAndRepoAndSha.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: postByOwnerAndRepoAndSha.path(owner, repo, sha),
      contentType: "application/json",
    });
    try {
      assert.param("owner")(() => typia.assert(owner));
      assert.param("repo")(() => typia.assert(repo));
      assert.param("sha")(() => typia.assert(sha));
      assert.body(() => typia.assert(body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
