import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IApiReposDependencyGraphSbom } from "../../../../structures/IApiReposDependencyGraphSbom";
import { dependency_minus_graph_minus_spdx_minus_sbom } from "../../../../structures/dependency_minus_graph_minus_spdx_minus_sbom";
/**
 * Export a software bill of materials (SBOM) for a repository.
 * Exports the software bill of materials (SBOM) for a repository in SPDX JSON format.
 *
 * @tag dependency-graph
 * @path repos/:owner/:repo/dependency-graph/sbom
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getByOwnerAndRepo(
  connection: IConnection<getByOwnerAndRepo.Headers>,
  owner: string,
  repo: string,
): Promise<getByOwnerAndRepo.Output> {
  return !!connection.simulate
    ? getByOwnerAndRepo.simulate(connection, owner, repo)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getByOwnerAndRepo.METADATA,
          path: getByOwnerAndRepo.path(owner, repo),
          status: null,
        },
      );
}
export namespace getByOwnerAndRepo {
  export type Headers = IApiReposDependencyGraphSbom.GetHeader;
  export type Output = dependency_minus_graph_minus_spdx_minus_sbom;

  export const METADATA = {
    method: "GET",
    path: "/repos/:owner/:repo/dependency-graph/sbom",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (owner: string, repo: string) =>
    `/repos/${encodeURIComponent(owner ?? "null")}/${encodeURIComponent(repo ?? "null")}/dependency-graph/sbom`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): dependency_minus_graph_minus_spdx_minus_sbom =>
    typia.random<dependency_minus_graph_minus_spdx_minus_sbom>(g);
  export const simulate = (
    connection: IConnection<getByOwnerAndRepo.Headers>,
    owner: string,
    repo: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: getByOwnerAndRepo.path(owner, repo),
      contentType: "application/json",
    });
    try {
      assert.param("owner")(() => typia.assert(owner));
      assert.param("repo")(() => typia.assert(repo));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
