import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IApiAppHookDeliveriesAttempts } from "../../../../../structures/IApiAppHookDeliveriesAttempts";
/**
 * Redeliver a delivery for an app webhook.
 * Redeliver a delivery for the webhook configured for a GitHub App.
 *
 * You must use a [JWT](https://docs.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app) to access this endpoint.
 *
 * @tag apps
 * @path app/hook/deliveries/:delivery_id/attempts
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function postByDelivery_id(
  connection: IConnection<postByDelivery_id.Headers>,
  delivery_id: string,
): Promise<void> {
  return !!connection.simulate
    ? postByDelivery_id.simulate(connection, delivery_id)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...postByDelivery_id.METADATA,
          path: postByDelivery_id.path(delivery_id),
          status: null,
        },
      );
}
export namespace postByDelivery_id {
  export type Headers = IApiAppHookDeliveriesAttempts.PostHeader;

  export const METADATA = {
    method: "POST",
    path: "/app/hook/deliveries/:delivery_id/attempts",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (delivery_id: string) =>
    `/app/hook/deliveries/${encodeURIComponent(delivery_id ?? "null")}/attempts`;
  export const random = (g?: Partial<typia.IRandomGenerator>): void =>
    typia.random<void>(g);
  export const simulate = (
    connection: IConnection<postByDelivery_id.Headers>,
    delivery_id: string,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: postByDelivery_id.path(delivery_id),
      contentType: "application/json",
    });
    try {
      assert.param("delivery_id")(() => typia.assert(delivery_id));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
