import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import { IApiOrgsHooksDeliveries } from "../../../../structures/IApiOrgsHooksDeliveries";
import { hook_minus_delivery } from "../../../../structures/hook_minus_delivery";
import { hook_minus_delivery_minus_item } from "../../../../structures/hook_minus_delivery_minus_item";

export * as attempts from "./attempts";
/**
 * List deliveries for an organization webhook.
 * Returns a list of webhook deliveries for a webhook configured in an organization.
 *
 * You must be an organization owner to use this endpoint.
 *
 * OAuth app tokens and personal access tokens (classic) need `admin:org_hook` scope. OAuth apps cannot list, view, or edit
 * webhooks that they did not create and users cannot list, view, or edit webhooks that were created by OAuth apps.
 *
 * @tag orgs
 * @path orgs/:org/hooks/:hook_id/deliveries
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getByOrgAndHook_id(
  connection: IConnection<getByOrgAndHook_id.Headers>,
  org: string,
  hook_id: string,
  query: getByOrgAndHook_id.Query,
): Promise<getByOrgAndHook_id.Output> {
  return !!connection.simulate
    ? getByOrgAndHook_id.simulate(connection, org, hook_id, query)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getByOrgAndHook_id.METADATA,
          path: getByOrgAndHook_id.path(org, hook_id, query),
          status: null,
        },
      );
}
export namespace getByOrgAndHook_id {
  export type Headers = IApiOrgsHooksDeliveries.GetHeader;
  export type Query = IApiOrgsHooksDeliveries.GetQuery;
  export type Output = hook_minus_delivery_minus_item[];

  export const METADATA = {
    method: "GET",
    path: "/orgs/:org/hooks/:hook_id/deliveries",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (
    org: string,
    hook_id: string,
    query: getByOrgAndHook_id.Query,
  ) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = `/orgs/${encodeURIComponent(org ?? "null")}/hooks/${encodeURIComponent(hook_id ?? "null")}/deliveries`;
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): hook_minus_delivery_minus_item[] =>
    typia.random<hook_minus_delivery_minus_item[]>(g);
  export const simulate = (
    connection: IConnection<getByOrgAndHook_id.Headers>,
    org: string,
    hook_id: string,
    query: getByOrgAndHook_id.Query,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: getByOrgAndHook_id.path(org, hook_id, query),
      contentType: "application/json",
    });
    try {
      assert.param("org")(() => typia.assert(org));
      assert.param("hook_id")(() => typia.assert(hook_id));
      assert.query(() => typia.assert(query));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
/**
 * Get a webhook delivery for an organization webhook.
 * Returns a delivery for a webhook configured in an organization.
 *
 * You must be an organization owner to use this endpoint.
 *
 * OAuth app tokens and personal access tokens (classic) need `admin:org_hook` scope. OAuth apps cannot list, view, or edit
 * webhooks that they did not create and users cannot list, view, or edit webhooks that were created by OAuth apps.
 *
 * @tag orgs
 * @path orgs/:org/hooks/:hook_id/deliveries/:delivery_id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getByOrgAndHook_idAndDelivery_id(
  connection: IConnection<getByOrgAndHook_idAndDelivery_id.Headers>,
  org: string,
  hook_id: string,
  delivery_id: string,
): Promise<getByOrgAndHook_idAndDelivery_id.Output> {
  return !!connection.simulate
    ? getByOrgAndHook_idAndDelivery_id.simulate(
        connection,
        org,
        hook_id,
        delivery_id,
      )
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getByOrgAndHook_idAndDelivery_id.METADATA,
          path: getByOrgAndHook_idAndDelivery_id.path(
            org,
            hook_id,
            delivery_id,
          ),
          status: null,
        },
      );
}
export namespace getByOrgAndHook_idAndDelivery_id {
  export type Headers = IApiOrgsHooksDeliveries.GetHeader;
  export type Output = hook_minus_delivery;

  export const METADATA = {
    method: "GET",
    path: "/orgs/:org/hooks/:hook_id/deliveries/:delivery_id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (org: string, hook_id: string, delivery_id: string) =>
    `/orgs/${encodeURIComponent(org ?? "null")}/hooks/${encodeURIComponent(hook_id ?? "null")}/deliveries/${encodeURIComponent(delivery_id ?? "null")}`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): hook_minus_delivery => typia.random<hook_minus_delivery>(g);
  export const simulate = (
    connection: IConnection<getByOrgAndHook_idAndDelivery_id.Headers>,
    org: string,
    hook_id: string,
    delivery_id: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: getByOrgAndHook_idAndDelivery_id.path(org, hook_id, delivery_id),
      contentType: "application/json",
    });
    try {
      assert.param("org")(() => typia.assert(org));
      assert.param("hook_id")(() => typia.assert(hook_id));
      assert.param("delivery_id")(() => typia.assert(delivery_id));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
