import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import { IApiTeamsMemberships } from "../../../structures/IApiTeamsMemberships";
import { body } from "../../../structures/body";
import { team_minus_membership } from "../../../structures/team_minus_membership";

/**
 * Get team membership for a user (Legacy).
 * > [!WARNING]
 * > **Deprecation notice:** This endpoint route is deprecated and will be removed from the Teams API. We recommend migrating your existing code to use the new [Get team membership for a user](https://docs.github.com/rest/teams/members#get-team-membership-for-a-user) endpoint.
 *
 * Team members will include the members of child teams.
 *
 * To get a user's membership with a team, the team must be visible to the authenticated user.
 *
 * **Note:**
 * The response contains the `state` of the membership and the member's `role`.
 *
 * The `role` for organization owners is set to `maintainer`. For more information about `maintainer` roles, see [Create a team](https://docs.github.com/rest/teams/teams#create-a-team).
 *
 * @tag teams
 * @deprecated
 * @path teams/:team_id/memberships/:username
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getByTeam_idAndUsername(
  connection: IConnection<getByTeam_idAndUsername.Headers>,
  team_id: string,
  username: string,
): Promise<getByTeam_idAndUsername.Output> {
  return !!connection.simulate
    ? getByTeam_idAndUsername.simulate(connection, team_id, username)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getByTeam_idAndUsername.METADATA,
          path: getByTeam_idAndUsername.path(team_id, username),
          status: null,
        },
      );
}
export namespace getByTeam_idAndUsername {
  export type Headers = IApiTeamsMemberships.GetHeader;
  export type Output = team_minus_membership;

  export const METADATA = {
    method: "GET",
    path: "/teams/:team_id/memberships/:username",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (team_id: string, username: string) =>
    `/teams/${encodeURIComponent(team_id ?? "null")}/memberships/${encodeURIComponent(username ?? "null")}`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): team_minus_membership => typia.random<team_minus_membership>(g);
  export const simulate = (
    connection: IConnection<getByTeam_idAndUsername.Headers>,
    team_id: string,
    username: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: getByTeam_idAndUsername.path(team_id, username),
      contentType: "application/json",
    });
    try {
      assert.param("team_id")(() => typia.assert(team_id));
      assert.param("username")(() => typia.assert(username));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
/**
 * Add or update team membership for a user (Legacy).
 * > [!WARNING]
 * > **Deprecation notice:** This endpoint route is deprecated and will be removed from the Teams API. We recommend migrating your existing code to use the new [Add or update team membership for a user](https://docs.github.com/rest/teams/members#add-or-update-team-membership-for-a-user) endpoint.
 *
 * Team synchronization is available for organizations using GitHub Enterprise Cloud. For more information, see [GitHub's products](https://docs.github.com/github/getting-started-with-github/githubs-products) in the GitHub Help documentation.
 *
 * If the user is already a member of the team's organization, this endpoint will add the user to the team. To add a membership between an organization member and a team, the authenticated user must be an organization owner or a team maintainer.
 *
 * > [!NOTE]
 * > When you have team synchronization set up for a team with your organization's identity provider (IdP), you will see an error if you attempt to use the API for making changes to the team's membership. If you have access to manage group membership in your IdP, you can manage GitHub team membership through your identity provider, which automatically adds and removes team members in an organization. For more information, see "[Synchronizing teams between your identity provider and GitHub](https://docs.github.com/articles/synchronizing-teams-between-your-identity-provider-and-github/)."
 *
 * If the user is unaffiliated with the team's organization, this endpoint will send an invitation to the user via email. This newly-created membership will be in the "pending" state until the user accepts the invitation, at which point the membership will transition to the "active" state and the user will be added as a member of the team. To add a membership between an unaffiliated user and a team, the authenticated user must be an organization owner.
 *
 * If the user is already a member of the team, this endpoint will update the role of the team member's role. To update the membership of a team member, the authenticated user must be an organization owner or a team maintainer.
 *
 * @tag teams
 * @deprecated
 * @path teams/:team_id/memberships/:username
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function putByTeam_idAndUsername(
  connection: IConnection<putByTeam_idAndUsername.Headers>,
  team_id: string,
  username: string,
  body: putByTeam_idAndUsername.Input,
): Promise<putByTeam_idAndUsername.Output> {
  return !!connection.simulate
    ? putByTeam_idAndUsername.simulate(connection, team_id, username, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...putByTeam_idAndUsername.METADATA,
          path: putByTeam_idAndUsername.path(team_id, username),
          status: null,
        },
        body,
      );
}
export namespace putByTeam_idAndUsername {
  export type Headers = IApiTeamsMemberships.PutHeader;
  export type Input = body;
  export type Output = team_minus_membership;

  export const METADATA = {
    method: "PUT",
    path: "/teams/:team_id/memberships/:username",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (team_id: string, username: string) =>
    `/teams/${encodeURIComponent(team_id ?? "null")}/memberships/${encodeURIComponent(username ?? "null")}`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): team_minus_membership => typia.random<team_minus_membership>(g);
  export const simulate = (
    connection: IConnection<putByTeam_idAndUsername.Headers>,
    team_id: string,
    username: string,
    body: putByTeam_idAndUsername.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: putByTeam_idAndUsername.path(team_id, username),
      contentType: "application/json",
    });
    try {
      assert.param("team_id")(() => typia.assert(team_id));
      assert.param("username")(() => typia.assert(username));
      assert.body(() => typia.assert(body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
/**
 * Remove team membership for a user (Legacy).
 * > [!WARNING]
 * > **Deprecation notice:** This endpoint route is deprecated and will be removed from the Teams API. We recommend migrating your existing code to use the new [Remove team membership for a user](https://docs.github.com/rest/teams/members#remove-team-membership-for-a-user) endpoint.
 *
 * Team synchronization is available for organizations using GitHub Enterprise Cloud. For more information, see [GitHub's products](https://docs.github.com/github/getting-started-with-github/githubs-products) in the GitHub Help documentation.
 *
 * To remove a membership between a user and a team, the authenticated user must have 'admin' permissions to the team or be an owner of the organization that the team is associated with. Removing team membership does not delete the user, it just removes their membership from the team.
 *
 * > [!NOTE]
 * > When you have team synchronization set up for a team with your organization's identity provider (IdP), you will see an error if you attempt to use the API for making changes to the team's membership. If you have access to manage group membership in your IdP, you can manage GitHub team membership through your identity provider, which automatically adds and removes team members in an organization. For more information, see "[Synchronizing teams between your identity provider and GitHub](https://docs.github.com/articles/synchronizing-teams-between-your-identity-provider-and-github/)."
 *
 * @tag teams
 * @deprecated
 * @path teams/:team_id/memberships/:username
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function eraseByTeam_idAndUsername(
  connection: IConnection<eraseByTeam_idAndUsername.Headers>,
  team_id: string,
  username: string,
): Promise<void> {
  return !!connection.simulate
    ? eraseByTeam_idAndUsername.simulate(connection, team_id, username)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...eraseByTeam_idAndUsername.METADATA,
          path: eraseByTeam_idAndUsername.path(team_id, username),
          status: null,
        },
      );
}
export namespace eraseByTeam_idAndUsername {
  export type Headers = IApiTeamsMemberships.DeleteHeader;

  export const METADATA = {
    method: "DELETE",
    path: "/teams/:team_id/memberships/:username",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (team_id: string, username: string) =>
    `/teams/${encodeURIComponent(team_id ?? "null")}/memberships/${encodeURIComponent(username ?? "null")}`;
  export const random = (g?: Partial<typia.IRandomGenerator>): void =>
    typia.random<void>(g);
  export const simulate = (
    connection: IConnection<eraseByTeam_idAndUsername.Headers>,
    team_id: string,
    username: string,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: eraseByTeam_idAndUsername.path(team_id, username),
      contentType: "application/json",
    });
    try {
      assert.param("team_id")(() => typia.assert(team_id));
      assert.param("username")(() => typia.assert(username));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
