import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IApiOrgsHooksDeliveriesAttempts } from "../../../../../structures/IApiOrgsHooksDeliveriesAttempts";
/**
 * Redeliver a delivery for an organization webhook.
 * Redeliver a delivery for a webhook configured in an organization.
 *
 * You must be an organization owner to use this endpoint.
 *
 * OAuth app tokens and personal access tokens (classic) need `admin:org_hook` scope. OAuth apps cannot list, view, or edit
 * webhooks that they did not create and users cannot list, view, or edit webhooks that were created by OAuth apps.
 *
 * @tag orgs
 * @path orgs/:org/hooks/:hook_id/deliveries/:delivery_id/attempts
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function postByOrgAndHook_idAndDelivery_id(
  connection: IConnection<postByOrgAndHook_idAndDelivery_id.Headers>,
  org: string,
  hook_id: string,
  delivery_id: string,
): Promise<void> {
  return !!connection.simulate
    ? postByOrgAndHook_idAndDelivery_id.simulate(
        connection,
        org,
        hook_id,
        delivery_id,
      )
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...postByOrgAndHook_idAndDelivery_id.METADATA,
          path: postByOrgAndHook_idAndDelivery_id.path(
            org,
            hook_id,
            delivery_id,
          ),
          status: null,
        },
      );
}
export namespace postByOrgAndHook_idAndDelivery_id {
  export type Headers = IApiOrgsHooksDeliveriesAttempts.PostHeader;

  export const METADATA = {
    method: "POST",
    path: "/orgs/:org/hooks/:hook_id/deliveries/:delivery_id/attempts",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (org: string, hook_id: string, delivery_id: string) =>
    `/orgs/${encodeURIComponent(org ?? "null")}/hooks/${encodeURIComponent(hook_id ?? "null")}/deliveries/${encodeURIComponent(delivery_id ?? "null")}/attempts`;
  export const random = (g?: Partial<typia.IRandomGenerator>): void =>
    typia.random<void>(g);
  export const simulate = (
    connection: IConnection<postByOrgAndHook_idAndDelivery_id.Headers>,
    org: string,
    hook_id: string,
    delivery_id: string,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: postByOrgAndHook_idAndDelivery_id.path(org, hook_id, delivery_id),
      contentType: "application/json",
    });
    try {
      assert.param("org")(() => typia.assert(org));
      assert.param("hook_id")(() => typia.assert(hook_id));
      assert.param("delivery_id")(() => typia.assert(delivery_id));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
