import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import { IApiOrgsTeamsDiscussionsComments } from "../../../../../structures/IApiOrgsTeamsDiscussionsComments";
import { body } from "../../../../../structures/body";
import { team_minus_discussion_minus_comment } from "../../../../../structures/team_minus_discussion_minus_comment";

export * as reactions from "./reactions";
/**
 * List discussion comments.
 * List all comments on a team discussion.
 *
 * > [!NOTE]
 * > You can also specify a team by `org_id` and `team_id` using the route `GET /organizations/{org_id}/team/{team_id}/discussions/{discussion_number}/comments`.
 *
 * OAuth app tokens and personal access tokens (classic) need the `read:discussion` scope to use this endpoint.
 *
 * @tag teams
 * @path orgs/:org/teams/:team_slug/discussions/:discussion_number/comments
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getByOrgAndTeam_slugAndDiscussion_number(
  connection: IConnection<getByOrgAndTeam_slugAndDiscussion_number.Headers>,
  org: string,
  team_slug: string,
  discussion_number: string,
): Promise<getByOrgAndTeam_slugAndDiscussion_number.Output> {
  return !!connection.simulate
    ? getByOrgAndTeam_slugAndDiscussion_number.simulate(
        connection,
        org,
        team_slug,
        discussion_number,
      )
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getByOrgAndTeam_slugAndDiscussion_number.METADATA,
          path: getByOrgAndTeam_slugAndDiscussion_number.path(
            org,
            team_slug,
            discussion_number,
          ),
          status: null,
        },
      );
}
export namespace getByOrgAndTeam_slugAndDiscussion_number {
  export type Headers = IApiOrgsTeamsDiscussionsComments.GetHeader;
  export type Output = team_minus_discussion_minus_comment[];

  export const METADATA = {
    method: "GET",
    path: "/orgs/:org/teams/:team_slug/discussions/:discussion_number/comments",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (
    org: string,
    team_slug: string,
    discussion_number: string,
  ) =>
    `/orgs/${encodeURIComponent(org ?? "null")}/teams/${encodeURIComponent(team_slug ?? "null")}/discussions/${encodeURIComponent(discussion_number ?? "null")}/comments`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): team_minus_discussion_minus_comment[] =>
    typia.random<team_minus_discussion_minus_comment[]>(g);
  export const simulate = (
    connection: IConnection<getByOrgAndTeam_slugAndDiscussion_number.Headers>,
    org: string,
    team_slug: string,
    discussion_number: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: getByOrgAndTeam_slugAndDiscussion_number.path(
        org,
        team_slug,
        discussion_number,
      ),
      contentType: "application/json",
    });
    try {
      assert.param("org")(() => typia.assert(org));
      assert.param("team_slug")(() => typia.assert(team_slug));
      assert.param("discussion_number")(() => typia.assert(discussion_number));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
/**
 * Create a discussion comment.
 * Creates a new comment on a team discussion.
 *
 * This endpoint triggers [notifications](https://docs.github.com/github/managing-subscriptions-and-notifications-on-github/about-notifications). Creating content too quickly using this endpoint may result in secondary rate limiting. For more information, see "[Rate limits for the API](https://docs.github.com/rest/using-the-rest-api/rate-limits-for-the-rest-api#about-secondary-rate-limits)" and "[Best practices for using the REST API](https://docs.github.com/rest/guides/best-practices-for-using-the-rest-api)."
 *
 * > [!NOTE]
 * > You can also specify a team by `org_id` and `team_id` using the route `POST /organizations/{org_id}/team/{team_id}/discussions/{discussion_number}/comments`.
 *
 * OAuth app tokens and personal access tokens (classic) need the `write:discussion` scope to use this endpoint.
 *
 * @tag teams
 * @path orgs/:org/teams/:team_slug/discussions/:discussion_number/comments
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function postByOrgAndTeam_slugAndDiscussion_number(
  connection: IConnection<postByOrgAndTeam_slugAndDiscussion_number.Headers>,
  org: string,
  team_slug: string,
  discussion_number: string,
  body: postByOrgAndTeam_slugAndDiscussion_number.Input,
): Promise<postByOrgAndTeam_slugAndDiscussion_number.Output> {
  return !!connection.simulate
    ? postByOrgAndTeam_slugAndDiscussion_number.simulate(
        connection,
        org,
        team_slug,
        discussion_number,
        body,
      )
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...postByOrgAndTeam_slugAndDiscussion_number.METADATA,
          path: postByOrgAndTeam_slugAndDiscussion_number.path(
            org,
            team_slug,
            discussion_number,
          ),
          status: null,
        },
        body,
      );
}
export namespace postByOrgAndTeam_slugAndDiscussion_number {
  export type Headers = IApiOrgsTeamsDiscussionsComments.PostHeader;
  export type Input = body;
  export type Output = team_minus_discussion_minus_comment;

  export const METADATA = {
    method: "POST",
    path: "/orgs/:org/teams/:team_slug/discussions/:discussion_number/comments",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (
    org: string,
    team_slug: string,
    discussion_number: string,
  ) =>
    `/orgs/${encodeURIComponent(org ?? "null")}/teams/${encodeURIComponent(team_slug ?? "null")}/discussions/${encodeURIComponent(discussion_number ?? "null")}/comments`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): team_minus_discussion_minus_comment =>
    typia.random<team_minus_discussion_minus_comment>(g);
  export const simulate = (
    connection: IConnection<postByOrgAndTeam_slugAndDiscussion_number.Headers>,
    org: string,
    team_slug: string,
    discussion_number: string,
    body: postByOrgAndTeam_slugAndDiscussion_number.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: postByOrgAndTeam_slugAndDiscussion_number.path(
        org,
        team_slug,
        discussion_number,
      ),
      contentType: "application/json",
    });
    try {
      assert.param("org")(() => typia.assert(org));
      assert.param("team_slug")(() => typia.assert(team_slug));
      assert.param("discussion_number")(() => typia.assert(discussion_number));
      assert.body(() => typia.assert(body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
/**
 * Get a discussion comment.
 * Get a specific comment on a team discussion.
 *
 * > [!NOTE]
 * > You can also specify a team by `org_id` and `team_id` using the route `GET /organizations/{org_id}/team/{team_id}/discussions/{discussion_number}/comments/{comment_number}`.
 *
 * OAuth app tokens and personal access tokens (classic) need the `read:discussion` scope to use this endpoint.
 *
 * @tag teams
 * @path orgs/:org/teams/:team_slug/discussions/:discussion_number/comments/:comment_number
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getByOrgAndTeam_slugAndDiscussion_numberAndComment_number(
  connection: IConnection<getByOrgAndTeam_slugAndDiscussion_numberAndComment_number.Headers>,
  org: string,
  team_slug: string,
  discussion_number: string,
  comment_number: string,
): Promise<getByOrgAndTeam_slugAndDiscussion_numberAndComment_number.Output> {
  return !!connection.simulate
    ? getByOrgAndTeam_slugAndDiscussion_numberAndComment_number.simulate(
        connection,
        org,
        team_slug,
        discussion_number,
        comment_number,
      )
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getByOrgAndTeam_slugAndDiscussion_numberAndComment_number.METADATA,
          path: getByOrgAndTeam_slugAndDiscussion_numberAndComment_number.path(
            org,
            team_slug,
            discussion_number,
            comment_number,
          ),
          status: null,
        },
      );
}
export namespace getByOrgAndTeam_slugAndDiscussion_numberAndComment_number {
  export type Headers = IApiOrgsTeamsDiscussionsComments.GetHeader;
  export type Output = team_minus_discussion_minus_comment;

  export const METADATA = {
    method: "GET",
    path: "/orgs/:org/teams/:team_slug/discussions/:discussion_number/comments/:comment_number",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (
    org: string,
    team_slug: string,
    discussion_number: string,
    comment_number: string,
  ) =>
    `/orgs/${encodeURIComponent(org ?? "null")}/teams/${encodeURIComponent(team_slug ?? "null")}/discussions/${encodeURIComponent(discussion_number ?? "null")}/comments/${encodeURIComponent(comment_number ?? "null")}`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): team_minus_discussion_minus_comment =>
    typia.random<team_minus_discussion_minus_comment>(g);
  export const simulate = (
    connection: IConnection<getByOrgAndTeam_slugAndDiscussion_numberAndComment_number.Headers>,
    org: string,
    team_slug: string,
    discussion_number: string,
    comment_number: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: getByOrgAndTeam_slugAndDiscussion_numberAndComment_number.path(
        org,
        team_slug,
        discussion_number,
        comment_number,
      ),
      contentType: "application/json",
    });
    try {
      assert.param("org")(() => typia.assert(org));
      assert.param("team_slug")(() => typia.assert(team_slug));
      assert.param("discussion_number")(() => typia.assert(discussion_number));
      assert.param("comment_number")(() => typia.assert(comment_number));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
/**
 * Update a discussion comment.
 * Edits the body text of a discussion comment.
 *
 * > [!NOTE]
 * > You can also specify a team by `org_id` and `team_id` using the route `PATCH /organizations/{org_id}/team/{team_id}/discussions/{discussion_number}/comments/{comment_number}`.
 *
 * OAuth app tokens and personal access tokens (classic) need the `write:discussion` scope to use this endpoint.
 *
 * @tag teams
 * @path orgs/:org/teams/:team_slug/discussions/:discussion_number/comments/:comment_number
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function patchByOrgAndTeam_slugAndDiscussion_numberAndComment_number(
  connection: IConnection<patchByOrgAndTeam_slugAndDiscussion_numberAndComment_number.Headers>,
  org: string,
  team_slug: string,
  discussion_number: string,
  comment_number: string,
  body: patchByOrgAndTeam_slugAndDiscussion_numberAndComment_number.Input,
): Promise<patchByOrgAndTeam_slugAndDiscussion_numberAndComment_number.Output> {
  return !!connection.simulate
    ? patchByOrgAndTeam_slugAndDiscussion_numberAndComment_number.simulate(
        connection,
        org,
        team_slug,
        discussion_number,
        comment_number,
        body,
      )
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...patchByOrgAndTeam_slugAndDiscussion_numberAndComment_number.METADATA,
          path: patchByOrgAndTeam_slugAndDiscussion_numberAndComment_number.path(
            org,
            team_slug,
            discussion_number,
            comment_number,
          ),
          status: null,
        },
        body,
      );
}
export namespace patchByOrgAndTeam_slugAndDiscussion_numberAndComment_number {
  export type Headers = IApiOrgsTeamsDiscussionsComments.PatchHeader;
  export type Input = body;
  export type Output = team_minus_discussion_minus_comment;

  export const METADATA = {
    method: "PATCH",
    path: "/orgs/:org/teams/:team_slug/discussions/:discussion_number/comments/:comment_number",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (
    org: string,
    team_slug: string,
    discussion_number: string,
    comment_number: string,
  ) =>
    `/orgs/${encodeURIComponent(org ?? "null")}/teams/${encodeURIComponent(team_slug ?? "null")}/discussions/${encodeURIComponent(discussion_number ?? "null")}/comments/${encodeURIComponent(comment_number ?? "null")}`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): team_minus_discussion_minus_comment =>
    typia.random<team_minus_discussion_minus_comment>(g);
  export const simulate = (
    connection: IConnection<patchByOrgAndTeam_slugAndDiscussion_numberAndComment_number.Headers>,
    org: string,
    team_slug: string,
    discussion_number: string,
    comment_number: string,
    body: patchByOrgAndTeam_slugAndDiscussion_numberAndComment_number.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: patchByOrgAndTeam_slugAndDiscussion_numberAndComment_number.path(
        org,
        team_slug,
        discussion_number,
        comment_number,
      ),
      contentType: "application/json",
    });
    try {
      assert.param("org")(() => typia.assert(org));
      assert.param("team_slug")(() => typia.assert(team_slug));
      assert.param("discussion_number")(() => typia.assert(discussion_number));
      assert.param("comment_number")(() => typia.assert(comment_number));
      assert.body(() => typia.assert(body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
/**
 * Delete a discussion comment.
 * Deletes a comment on a team discussion.
 *
 * > [!NOTE]
 * > You can also specify a team by `org_id` and `team_id` using the route `DELETE /organizations/{org_id}/team/{team_id}/discussions/{discussion_number}/comments/{comment_number}`.
 *
 * OAuth app tokens and personal access tokens (classic) need the `write:discussion` scope to use this endpoint.
 *
 * @tag teams
 * @path orgs/:org/teams/:team_slug/discussions/:discussion_number/comments/:comment_number
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function eraseByOrgAndTeam_slugAndDiscussion_numberAndComment_number(
  connection: IConnection<eraseByOrgAndTeam_slugAndDiscussion_numberAndComment_number.Headers>,
  org: string,
  team_slug: string,
  discussion_number: string,
  comment_number: string,
): Promise<void> {
  return !!connection.simulate
    ? eraseByOrgAndTeam_slugAndDiscussion_numberAndComment_number.simulate(
        connection,
        org,
        team_slug,
        discussion_number,
        comment_number,
      )
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...eraseByOrgAndTeam_slugAndDiscussion_numberAndComment_number.METADATA,
          path: eraseByOrgAndTeam_slugAndDiscussion_numberAndComment_number.path(
            org,
            team_slug,
            discussion_number,
            comment_number,
          ),
          status: null,
        },
      );
}
export namespace eraseByOrgAndTeam_slugAndDiscussion_numberAndComment_number {
  export type Headers = IApiOrgsTeamsDiscussionsComments.DeleteHeader;

  export const METADATA = {
    method: "DELETE",
    path: "/orgs/:org/teams/:team_slug/discussions/:discussion_number/comments/:comment_number",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (
    org: string,
    team_slug: string,
    discussion_number: string,
    comment_number: string,
  ) =>
    `/orgs/${encodeURIComponent(org ?? "null")}/teams/${encodeURIComponent(team_slug ?? "null")}/discussions/${encodeURIComponent(discussion_number ?? "null")}/comments/${encodeURIComponent(comment_number ?? "null")}`;
  export const random = (g?: Partial<typia.IRandomGenerator>): void =>
    typia.random<void>(g);
  export const simulate = (
    connection: IConnection<eraseByOrgAndTeam_slugAndDiscussion_numberAndComment_number.Headers>,
    org: string,
    team_slug: string,
    discussion_number: string,
    comment_number: string,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: eraseByOrgAndTeam_slugAndDiscussion_numberAndComment_number.path(
        org,
        team_slug,
        discussion_number,
        comment_number,
      ),
      contentType: "application/json",
    });
    try {
      assert.param("org")(() => typia.assert(org));
      assert.param("team_slug")(() => typia.assert(team_slug));
      assert.param("discussion_number")(() => typia.assert(discussion_number));
      assert.param("comment_number")(() => typia.assert(comment_number));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
