import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IApiOrgsActionsRunners } from "../../../../structures/IApiOrgsActionsRunners";
import { response } from "../../../../structures/response";
import { runner } from "../../../../structures/runner";
export * as downloads from "./downloads";
export * as generate_jitconfig from "./generate_jitconfig";
export * as registration_token from "./registration_token";
export * as remove_token from "./remove_token";
export * as labels from "./labels";
/**
 * List self-hosted runners for an organization.
 * Lists all self-hosted runners configured in an organization.
 *
 * Authenticated users must have admin access to the organization to use this endpoint.
 *
 * OAuth app tokens and personal access tokens (classic) need the `admin:org` scope to use this endpoint. If the repository is private, the `repo` scope is also required.
 *
 * @tag actions
 * @path orgs/:org/actions/runners
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getByOrg(
  connection: IConnection<getByOrg.Headers>,
  org: string,
  query: getByOrg.Query,
): Promise<getByOrg.Output> {
  return !!connection.simulate
    ? getByOrg.simulate(connection, org, query)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getByOrg.METADATA,
          path: getByOrg.path(org, query),
          status: null,
        },
      );
}
export namespace getByOrg {
  export type Headers = IApiOrgsActionsRunners.GetHeader;
  export type Query = IApiOrgsActionsRunners.GetQuery;
  export type Output = response;

  export const METADATA = {
    method: "GET",
    path: "/orgs/:org/actions/runners",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (org: string, query: getByOrg.Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = `/orgs/${encodeURIComponent(org ?? "null")}/actions/runners`;
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (g?: Partial<typia.IRandomGenerator>): response =>
    typia.random<response>(g);
  export const simulate = (
    connection: IConnection<getByOrg.Headers>,
    org: string,
    query: getByOrg.Query,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: getByOrg.path(org, query),
      contentType: "application/json",
    });
    try {
      assert.param("org")(() => typia.assert(org));
      assert.query(() => typia.assert(query));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
/**
 * Get a self-hosted runner for an organization.
 * Gets a specific self-hosted runner configured in an organization.
 *
 * Authenticated users must have admin access to the organization to use this endpoint.
 *
 * OAuth app tokens and personal access tokens (classic) need the `admin:org` scope to use this endpoint. If the repository is private, the `repo` scope is also required.
 *
 * @tag actions
 * @path orgs/:org/actions/runners/:runner_id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getByOrgAndRunner_id(
  connection: IConnection<getByOrgAndRunner_id.Headers>,
  org: string,
  runner_id: string,
): Promise<getByOrgAndRunner_id.Output> {
  return !!connection.simulate
    ? getByOrgAndRunner_id.simulate(connection, org, runner_id)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getByOrgAndRunner_id.METADATA,
          path: getByOrgAndRunner_id.path(org, runner_id),
          status: null,
        },
      );
}
export namespace getByOrgAndRunner_id {
  export type Headers = IApiOrgsActionsRunners.GetHeader;
  export type Output = runner;

  export const METADATA = {
    method: "GET",
    path: "/orgs/:org/actions/runners/:runner_id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (org: string, runner_id: string) =>
    `/orgs/${encodeURIComponent(org ?? "null")}/actions/runners/${encodeURIComponent(runner_id ?? "null")}`;
  export const random = (g?: Partial<typia.IRandomGenerator>): runner =>
    typia.random<runner>(g);
  export const simulate = (
    connection: IConnection<getByOrgAndRunner_id.Headers>,
    org: string,
    runner_id: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: getByOrgAndRunner_id.path(org, runner_id),
      contentType: "application/json",
    });
    try {
      assert.param("org")(() => typia.assert(org));
      assert.param("runner_id")(() => typia.assert(runner_id));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
/**
 * Delete a self-hosted runner from an organization.
 * Forces the removal of a self-hosted runner from an organization. You can use this endpoint to completely remove the runner when the machine you were using no longer exists.
 *
 * Authenticated users must have admin access to the organization to use this endpoint.
 *
 * OAuth tokens and personal access tokens (classic) need the`admin:org` scope to use this endpoint. If the repository is private, OAuth tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
 *
 * @tag actions
 * @path orgs/:org/actions/runners/:runner_id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function eraseByOrgAndRunner_id(
  connection: IConnection<eraseByOrgAndRunner_id.Headers>,
  org: string,
  runner_id: string,
): Promise<void> {
  return !!connection.simulate
    ? eraseByOrgAndRunner_id.simulate(connection, org, runner_id)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...eraseByOrgAndRunner_id.METADATA,
          path: eraseByOrgAndRunner_id.path(org, runner_id),
          status: null,
        },
      );
}
export namespace eraseByOrgAndRunner_id {
  export type Headers = IApiOrgsActionsRunners.DeleteHeader;

  export const METADATA = {
    method: "DELETE",
    path: "/orgs/:org/actions/runners/:runner_id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (org: string, runner_id: string) =>
    `/orgs/${encodeURIComponent(org ?? "null")}/actions/runners/${encodeURIComponent(runner_id ?? "null")}`;
  export const random = (g?: Partial<typia.IRandomGenerator>): void =>
    typia.random<void>(g);
  export const simulate = (
    connection: IConnection<eraseByOrgAndRunner_id.Headers>,
    org: string,
    runner_id: string,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: eraseByOrgAndRunner_id.path(org, runner_id),
      contentType: "application/json",
    });
    try {
      assert.param("org")(() => typia.assert(org));
      assert.param("runner_id")(() => typia.assert(runner_id));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
