import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import { IApiOrgsInvitationsTeams } from "../../../../structures/IApiOrgsInvitationsTeams";
import { team } from "../../../../structures/team";

/**
 * List organization invitation teams.
 * List all teams associated with an invitation. In order to see invitations in an organization, the authenticated user must be an organization owner.
 *
 * @tag orgs
 * @path orgs/:org/invitations/:invitation_id/teams
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getByOrgAndInvitation_id(
  connection: IConnection<getByOrgAndInvitation_id.Headers>,
  org: string,
  invitation_id: string,
): Promise<getByOrgAndInvitation_id.Output> {
  return !!connection.simulate
    ? getByOrgAndInvitation_id.simulate(connection, org, invitation_id)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getByOrgAndInvitation_id.METADATA,
          path: getByOrgAndInvitation_id.path(org, invitation_id),
          status: null,
        },
      );
}
export namespace getByOrgAndInvitation_id {
  export type Headers = IApiOrgsInvitationsTeams.GetHeader;
  export type Output = team[];

  export const METADATA = {
    method: "GET",
    path: "/orgs/:org/invitations/:invitation_id/teams",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (org: string, invitation_id: string) =>
    `/orgs/${encodeURIComponent(org ?? "null")}/invitations/${encodeURIComponent(invitation_id ?? "null")}/teams`;
  export const random = (g?: Partial<typia.IRandomGenerator>): team[] =>
    typia.random<team[]>(g);
  export const simulate = (
    connection: IConnection<getByOrgAndInvitation_id.Headers>,
    org: string,
    invitation_id: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: getByOrgAndInvitation_id.path(org, invitation_id),
      contentType: "application/json",
    });
    try {
      assert.param("org")(() => typia.assert(org));
      assert.param("invitation_id")(() => typia.assert(invitation_id));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
