import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IApiOrgsMigrationsArchive } from "../../../../structures/IApiOrgsMigrationsArchive";
/**
 * Download an organization migration archive.
 * Fetches the URL to a migration archive.
 *
 * @tag migrations
 * @path orgs/:org/migrations/:migration_id/archive
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getByOrgAndMigration_id(
  connection: IConnection<getByOrgAndMigration_id.Headers>,
  org: string,
  migration_id: string,
): Promise<void> {
  return !!connection.simulate
    ? getByOrgAndMigration_id.simulate(connection, org, migration_id)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getByOrgAndMigration_id.METADATA,
          path: getByOrgAndMigration_id.path(org, migration_id),
          status: null,
        },
      );
}
export namespace getByOrgAndMigration_id {
  export type Headers = IApiOrgsMigrationsArchive.GetHeader;

  export const METADATA = {
    method: "GET",
    path: "/orgs/:org/migrations/:migration_id/archive",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (org: string, migration_id: string) =>
    `/orgs/${encodeURIComponent(org ?? "null")}/migrations/${encodeURIComponent(migration_id ?? "null")}/archive`;
  export const random = (g?: Partial<typia.IRandomGenerator>): void =>
    typia.random<void>(g);
  export const simulate = (
    connection: IConnection<getByOrgAndMigration_id.Headers>,
    org: string,
    migration_id: string,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: getByOrgAndMigration_id.path(org, migration_id),
      contentType: "application/json",
    });
    try {
      assert.param("org")(() => typia.assert(org));
      assert.param("migration_id")(() => typia.assert(migration_id));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
/**
 * Delete an organization migration archive.
 * Deletes a previous migration archive. Migration archives are automatically deleted after seven days.
 *
 * @tag migrations
 * @path orgs/:org/migrations/:migration_id/archive
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function eraseByOrgAndMigration_id(
  connection: IConnection<eraseByOrgAndMigration_id.Headers>,
  org: string,
  migration_id: string,
): Promise<void> {
  return !!connection.simulate
    ? eraseByOrgAndMigration_id.simulate(connection, org, migration_id)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...eraseByOrgAndMigration_id.METADATA,
          path: eraseByOrgAndMigration_id.path(org, migration_id),
          status: null,
        },
      );
}
export namespace eraseByOrgAndMigration_id {
  export type Headers = IApiOrgsMigrationsArchive.DeleteHeader;

  export const METADATA = {
    method: "DELETE",
    path: "/orgs/:org/migrations/:migration_id/archive",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (org: string, migration_id: string) =>
    `/orgs/${encodeURIComponent(org ?? "null")}/migrations/${encodeURIComponent(migration_id ?? "null")}/archive`;
  export const random = (g?: Partial<typia.IRandomGenerator>): void =>
    typia.random<void>(g);
  export const simulate = (
    connection: IConnection<eraseByOrgAndMigration_id.Headers>,
    org: string,
    migration_id: string,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: eraseByOrgAndMigration_id.path(org, migration_id),
      contentType: "application/json",
    });
    try {
      assert.param("org")(() => typia.assert(org));
      assert.param("migration_id")(() => typia.assert(migration_id));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
