import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

;
import { IApiReposImport } from "../../../structures/IApiReposImport";
import { import } from "../../../structures/import";
import { body } from "../../../structures/body";
export * as authors from "./authors";
export * as large_files from "./large_files";
export * as lfs from "./lfs";
/**
 * Get an import status.
 * View the progress of an import.
 *
 * > [!WARNING]
 * > **Deprecation notice:** Due to very low levels of usage and available alternatives, this endpoint is deprecated and will no longer be available from 00:00 UTC on April 12, 2024. For more details and alternatives, see the [changelog](https://gh.io/source-imports-api-deprecation).
 *
 * **Import status**
 *
 * This section includes details about the possible values of the `status` field of the Import Progress response.
 *
 * An import that does not have errors will progress through these steps:
 *
 * *   `detecting` - the "detection" step of the import is in progress because the request did not include a `vcs` parameter. The import is identifying the type of source control present at the URL.
 * *   `importing` - the "raw" step of the import is in progress. This is where commit data is fetched from the original repository. The import progress response will include `commit_count` (the total number of raw commits that will be imported) and `percent` (0 - 100, the current progress through the import).
 * *   `mapping` - the "rewrite" step of the import is in progress. This is where SVN branches are converted to Git branches, and where author updates are applied. The import progress response does not include progress information.
 * *   `pushing` - the "push" step of the import is in progress. This is where the importer updates the repository on GitHub. The import progress response will include `push_percent`, which is the percent value reported by `git push` when it is "Writing objects".
 * *   `complete` - the import is complete, and the repository is ready on GitHub.
 *
 * If there are problems, you will see one of these in the `status` field:
 *
 * *   `auth_failed` - the import requires authentication in order to connect to the original repository. To update authentication for the import, please see the [Update an import](https://docs.github.com/rest/migrations/source-imports#update-an-import) section.
 * *   `error` - the import encountered an error. The import progress response will include the `failed_step` and an error message. Contact [GitHub Support](https://support.github.com/contact?tags=dotcom-rest-api) for more information.
 * *   `detection_needs_auth` - the importer requires authentication for the originating repository to continue detection. To update authentication for the import, please see the [Update an import](https://docs.github.com/rest/migrations/source-imports#update-an-import) section.
 * *   `detection_found_nothing` - the importer didn't recognize any source control at the URL. To resolve, [Cancel the import](https://docs.github.com/rest/migrations/source-imports#cancel-an-import) and [retry](https://docs.github.com/rest/migrations/source-imports#start-an-import) with the correct URL.
 * *   `detection_found_multiple` - the importer found several projects or repositories at the provided URL. When this is the case, the Import Progress response will also include a `project_choices` field with the possible project choices as values. To update project choice, please see the [Update an import](https://docs.github.com/rest/migrations/source-imports#update-an-import) section.
 *
 * **The project_choices field**
 *
 * When multiple projects are found at the provided URL, the response hash will include a `project_choices` field, the value of which is an array of hashes each representing a project choice. The exact key/value pairs of the project hashes will differ depending on the version control type.
 *
 * **Git LFS related fields**
 *
 * This section includes details about Git LFS related fields that may be present in the Import Progress response.
 *
 * *   `use_lfs` - describes whether the import has been opted in or out of using Git LFS. The value can be `opt_in`, `opt_out`, or `undecided` if no action has been taken.
 * *   `has_large_files` - the boolean value describing whether files larger than 100MB were found during the `importing` step.
 * *   `large_files_size` - the total size in gigabytes of files larger than 100MB found in the originating repository.
 * *   `large_files_count` - the total number of files larger than 100MB found in the originating repository. To see a list of these files, make a "Get Large Files" request.
 *
 * @tag migrations
 * @deprecated
 * @path repos/:owner/:repo/import
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
*/
export async function getByOwnerAndRepo(connection: IConnection<getByOwnerAndRepo.Headers>, owner: string, repo: string): Promise<getByOwnerAndRepo.Output> {
    return !!connection.simulate ? getByOwnerAndRepo.simulate(connection, owner, repo) : PlainFetcher.fetch({
        ...connection,
        headers: {
            ...connection.headers,
            "Content-Type": "application/json"
        }
    }, {
        ...getByOwnerAndRepo.METADATA,
        path: getByOwnerAndRepo.path(owner, repo),
        status: null
    });
}
export namespace getByOwnerAndRepo {
    export type Headers = IApiReposImport.GetHeader;
    export type Output = import;
    
    ;
    export const METADATA = {
        method: "GET",
        path: "/repos/:owner/:repo/import",
        request: null,
        response: {
            type: "application/json",
            encrypted: false
        }
    } as const;
    
    ;
    export const path = (owner: string, repo: string) => `/repos/${encodeURIComponent(owner ?? "null")}/${encodeURIComponent(repo ?? "null")}/import`;
    export const random = (g?: Partial<typia.IRandomGenerator>): import => typia.random<import>(g);
    export const simulate = (connection: IConnection<getByOwnerAndRepo.Headers>, owner: string, repo: string): Output => {
        const assert = NestiaSimulator.assert({
            method: METADATA.method,
            host: connection.host,
            path: getByOwnerAndRepo.path(owner, repo),
            contentType: "application/json"
        });
        try {
            assert.param("owner")(() => typia.assert(owner));
            assert.param("repo")(() => typia.assert(repo));
        }
        catch (exp) {
            if (!typia.is<HttpError>(exp))
                throw exp;
            return {
                success: false,
                status: exp.status,
                headers: exp.headers,
                data: exp.toJSON().message
            } as any;
        }
        return random("object" === typeof connection.simulate && null !== connection.simulate ? connection.simulate : undefined);
    };
}
/**
 * Start an import.
 * Start a source import to a GitHub repository using GitHub Importer.
 * Importing into a GitHub repository with GitHub Actions enabled is not supported and will
 * return a status `422 Unprocessable Entity` response.
 *
 * > [!WARNING]
 * > **Deprecation notice:** Due to very low levels of usage and available alternatives, this endpoint is deprecated and will no longer be available from 00:00 UTC on April 12, 2024. For more details and alternatives, see the [changelog](https://gh.io/source-imports-api-deprecation).
 *
 * @tag migrations
 * @deprecated
 * @path repos/:owner/:repo/import
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
*/
export async function putByOwnerAndRepo(connection: IConnection<putByOwnerAndRepo.Headers>, owner: string, repo: string, body: putByOwnerAndRepo.Input): Promise<putByOwnerAndRepo.Output> {
    return !!connection.simulate ? putByOwnerAndRepo.simulate(connection, owner, repo, body) : PlainFetcher.fetch({
        ...connection,
        headers: {
            ...connection.headers,
            "Content-Type": "application/json"
        }
    }, {
        ...putByOwnerAndRepo.METADATA,
        path: putByOwnerAndRepo.path(owner, repo),
        status: null
    }, body);
}
export namespace putByOwnerAndRepo {
    export type Headers = IApiReposImport.PutHeader;
    export type Input = body;
    export type Output = import;
    
    ;
    export const METADATA = {
        method: "PUT",
        path: "/repos/:owner/:repo/import",
        request: {
            type: "application/json",
            encrypted: false
        },
        response: {
            type: "application/json",
            encrypted: false
        }
    } as const;
    
    ;
    export const path = (owner: string, repo: string) => `/repos/${encodeURIComponent(owner ?? "null")}/${encodeURIComponent(repo ?? "null")}/import`;
    export const random = (g?: Partial<typia.IRandomGenerator>): import => typia.random<import>(g);
    export const simulate = (connection: IConnection<putByOwnerAndRepo.Headers>, owner: string, repo: string, body: putByOwnerAndRepo.Input): Output => {
        const assert = NestiaSimulator.assert({
            method: METADATA.method,
            host: connection.host,
            path: putByOwnerAndRepo.path(owner, repo),
            contentType: "application/json"
        });
        try {
            assert.param("owner")(() => typia.assert(owner));
            assert.param("repo")(() => typia.assert(repo));
            assert.body(() => typia.assert(body));
        }
        catch (exp) {
            if (!typia.is<HttpError>(exp))
                throw exp;
            return {
                success: false,
                status: exp.status,
                headers: exp.headers,
                data: exp.toJSON().message
            } as any;
        }
        return random("object" === typeof connection.simulate && null !== connection.simulate ? connection.simulate : undefined);
    };
}
/**
 * Update an import.
 * An import can be updated with credentials or a project choice by passing in the appropriate parameters in this API
 * request. If no parameters are provided, the import will be restarted.
 *
 * Some servers (e.g. TFS servers) can have several projects at a single URL. In those cases the import progress will
 * have the status `detection_found_multiple` and the Import Progress response will include a `project_choices` array.
 * You can select the project to import by providing one of the objects in the `project_choices` array in the update request.
 *
 * > [!WARNING]
 * > **Deprecation notice:** Due to very low levels of usage and available alternatives, this endpoint is deprecated and will no longer be available from 00:00 UTC on April 12, 2024. For more details and alternatives, see the [changelog](https://gh.io/source-imports-api-deprecation).
 *
 * @tag migrations
 * @deprecated
 * @path repos/:owner/:repo/import
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
*/
export async function patchByOwnerAndRepo(connection: IConnection<patchByOwnerAndRepo.Headers>, owner: string, repo: string, body: patchByOwnerAndRepo.Input): Promise<patchByOwnerAndRepo.Output> {
    return !!connection.simulate ? patchByOwnerAndRepo.simulate(connection, owner, repo, body) : PlainFetcher.fetch({
        ...connection,
        headers: {
            ...connection.headers,
            "Content-Type": "application/json"
        }
    }, {
        ...patchByOwnerAndRepo.METADATA,
        path: patchByOwnerAndRepo.path(owner, repo),
        status: null
    }, body);
}
export namespace patchByOwnerAndRepo {
    export type Headers = IApiReposImport.PatchHeader;
    export type Input = body;
    export type Output = import;
    
    ;
    export const METADATA = {
        method: "PATCH",
        path: "/repos/:owner/:repo/import",
        request: {
            type: "application/json",
            encrypted: false
        },
        response: {
            type: "application/json",
            encrypted: false
        }
    } as const;
    
    ;
    export const path = (owner: string, repo: string) => `/repos/${encodeURIComponent(owner ?? "null")}/${encodeURIComponent(repo ?? "null")}/import`;
    export const random = (g?: Partial<typia.IRandomGenerator>): import => typia.random<import>(g);
    export const simulate = (connection: IConnection<patchByOwnerAndRepo.Headers>, owner: string, repo: string, body: patchByOwnerAndRepo.Input): Output => {
        const assert = NestiaSimulator.assert({
            method: METADATA.method,
            host: connection.host,
            path: patchByOwnerAndRepo.path(owner, repo),
            contentType: "application/json"
        });
        try {
            assert.param("owner")(() => typia.assert(owner));
            assert.param("repo")(() => typia.assert(repo));
            assert.body(() => typia.assert(body));
        }
        catch (exp) {
            if (!typia.is<HttpError>(exp))
                throw exp;
            return {
                success: false,
                status: exp.status,
                headers: exp.headers,
                data: exp.toJSON().message
            } as any;
        }
        return random("object" === typeof connection.simulate && null !== connection.simulate ? connection.simulate : undefined);
    };
}
/**
 * Cancel an import.
 * Stop an import for a repository.
 *
 * > [!WARNING]
 * > **Deprecation notice:** Due to very low levels of usage and available alternatives, this endpoint is deprecated and will no longer be available from 00:00 UTC on April 12, 2024. For more details and alternatives, see the [changelog](https://gh.io/source-imports-api-deprecation).
 *
 * @tag migrations
 * @deprecated
 * @path repos/:owner/:repo/import
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
*/
export async function eraseByOwnerAndRepo(connection: IConnection<eraseByOwnerAndRepo.Headers>, owner: string, repo: string): Promise<void> {
    return !!connection.simulate ? eraseByOwnerAndRepo.simulate(connection, owner, repo) : PlainFetcher.fetch({
        ...connection,
        headers: {
            ...connection.headers,
            "Content-Type": "application/json"
        }
    }, {
        ...eraseByOwnerAndRepo.METADATA,
        path: eraseByOwnerAndRepo.path(owner, repo),
        status: null
    });
}
export namespace eraseByOwnerAndRepo {
    export type Headers = IApiReposImport.DeleteHeader;
    
    ;
    export const METADATA = {
        method: "DELETE",
        path: "/repos/:owner/:repo/import",
        request: null,
        response: {
            type: "application/json",
            encrypted: false
        }
    } as const;
    
    ;
    export const path = (owner: string, repo: string) => `/repos/${encodeURIComponent(owner ?? "null")}/${encodeURIComponent(repo ?? "null")}/import`;
    export const random = (g?: Partial<typia.IRandomGenerator>): void => typia.random<void>(g);
    export const simulate = (connection: IConnection<eraseByOwnerAndRepo.Headers>, owner: string, repo: string): void => {
        const assert = NestiaSimulator.assert({
            method: METADATA.method,
            host: connection.host,
            path: eraseByOwnerAndRepo.path(owner, repo),
            contentType: "application/json"
        });
        try {
            assert.param("owner")(() => typia.assert(owner));
            assert.param("repo")(() => typia.assert(repo));
        }
        catch (exp) {
            if (!typia.is<HttpError>(exp))
                throw exp;
            return {
                success: false,
                status: exp.status,
                headers: exp.headers,
                data: exp.toJSON().message
            } as any;
        }
        return random("object" === typeof connection.simulate && null !== connection.simulate ? connection.simulate : undefined);
    };
}
