import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import { IApiOrgsCopilotBilling } from "../../../../structures/IApiOrgsCopilotBilling";
import { copilot_minus_organization_minus_details } from "../../../../structures/copilot_minus_organization_minus_details";

export * as seats from "./seats";
export * as selected_teams from "./selected_teams";
export * as selected_users from "./selected_users";
/**
 * Get Copilot seat information and settings for an organization.
 * > [!NOTE]
 * > This endpoint is in beta and is subject to change.
 *
 * Gets information about an organization's Copilot subscription, including seat breakdown
 * and feature policies. To configure these settings, go to your organization's settings on GitHub.com.
 * For more information, see "[Managing policies for Copilot in your organization](https://docs.github.com/copilot/managing-copilot/managing-policies-for-copilot-business-in-your-organization)".
 *
 * Only organization owners can view details about the organization's Copilot Business or Copilot Enterprise subscription.
 *
 * OAuth app tokens and personal access tokens (classic) need either the `manage_billing:copilot` or `read:org` scopes to use this endpoint.
 *
 * @tag copilot
 * @path orgs/:org/copilot/billing
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getByOrg(
  connection: IConnection<getByOrg.Headers>,
  org: string,
): Promise<getByOrg.Output> {
  return !!connection.simulate
    ? getByOrg.simulate(connection, org)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getByOrg.METADATA,
          path: getByOrg.path(org),
          status: null,
        },
      );
}
export namespace getByOrg {
  export type Headers = IApiOrgsCopilotBilling.GetHeader;
  export type Output = copilot_minus_organization_minus_details;

  export const METADATA = {
    method: "GET",
    path: "/orgs/:org/copilot/billing",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (org: string) =>
    `/orgs/${encodeURIComponent(org ?? "null")}/copilot/billing`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): copilot_minus_organization_minus_details =>
    typia.random<copilot_minus_organization_minus_details>(g);
  export const simulate = (
    connection: IConnection<getByOrg.Headers>,
    org: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: getByOrg.path(org),
      contentType: "application/json",
    });
    try {
      assert.param("org")(() => typia.assert(org));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
