import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import { IApiReposPullsUpdateBranch } from "../../../../structures/IApiReposPullsUpdateBranch";
import { body } from "../../../../structures/body";

/**
 * Update a pull request branch.
 * Updates the pull request branch with the latest upstream changes by merging HEAD from the base branch into the pull request branch.
 *
 * @tag pulls
 * @path repos/:owner/:repo/pulls/:pull_number/update-branch
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function putByOwnerAndRepoAndPull_number(
  connection: IConnection<putByOwnerAndRepoAndPull_number.Headers>,
  owner: string,
  repo: string,
  pull_number: string,
  body: putByOwnerAndRepoAndPull_number.Input,
): Promise<void> {
  return !!connection.simulate
    ? putByOwnerAndRepoAndPull_number.simulate(
        connection,
        owner,
        repo,
        pull_number,
        body,
      )
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...putByOwnerAndRepoAndPull_number.METADATA,
          path: putByOwnerAndRepoAndPull_number.path(owner, repo, pull_number),
          status: null,
        },
        body,
      );
}
export namespace putByOwnerAndRepoAndPull_number {
  export type Headers = IApiReposPullsUpdateBranch.PutHeader;
  export type Input = body;

  export const METADATA = {
    method: "PUT",
    path: "/repos/:owner/:repo/pulls/:pull_number/update-branch",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (owner: string, repo: string, pull_number: string) =>
    `/repos/${encodeURIComponent(owner ?? "null")}/${encodeURIComponent(repo ?? "null")}/pulls/${encodeURIComponent(pull_number ?? "null")}/update-branch`;
  export const random = (g?: Partial<typia.IRandomGenerator>): void =>
    typia.random<void>(g);
  export const simulate = (
    connection: IConnection<putByOwnerAndRepoAndPull_number.Headers>,
    owner: string,
    repo: string,
    pull_number: string,
    body: putByOwnerAndRepoAndPull_number.Input,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: putByOwnerAndRepoAndPull_number.path(owner, repo, pull_number),
      contentType: "application/json",
    });
    try {
      assert.param("owner")(() => typia.assert(owner));
      assert.param("repo")(() => typia.assert(repo));
      assert.param("pull_number")(() => typia.assert(pull_number));
      assert.body(() => typia.assert(body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
