import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IApiUserCodespacesMachines } from "../../../../structures/IApiUserCodespacesMachines";
import { response } from "../../../../structures/response";
/**
 * List machine types for a codespace.
 * List the machine types a codespace can transition to use.
 *
 * OAuth app tokens and personal access tokens (classic) need the `codespace` scope to use this endpoint.
 *
 * @tag codespaces
 * @path user/codespaces/:codespace_name/machines
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getByCodespace_name(
  connection: IConnection<getByCodespace_name.Headers>,
  codespace_name: string,
): Promise<getByCodespace_name.Output> {
  return !!connection.simulate
    ? getByCodespace_name.simulate(connection, codespace_name)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getByCodespace_name.METADATA,
          path: getByCodespace_name.path(codespace_name),
          status: null,
        },
      );
}
export namespace getByCodespace_name {
  export type Headers = IApiUserCodespacesMachines.GetHeader;
  export type Output = response;

  export const METADATA = {
    method: "GET",
    path: "/user/codespaces/:codespace_name/machines",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (codespace_name: string) =>
    `/user/codespaces/${encodeURIComponent(codespace_name ?? "null")}/machines`;
  export const random = (g?: Partial<typia.IRandomGenerator>): response =>
    typia.random<response>(g);
  export const simulate = (
    connection: IConnection<getByCodespace_name.Headers>,
    codespace_name: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: getByCodespace_name.path(codespace_name),
      contentType: "application/json",
    });
    try {
      assert.param("codespace_name")(() => typia.assert(codespace_name));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
