import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IApiReposIssuesLabels } from "../../../../structures/IApiReposIssuesLabels";
import { label } from "../../../../structures/label";
import { body } from "../../../../structures/body";
/**
 * List labels for an issue.
 * Lists all labels for an issue.
 *
 * @tag issues
 * @path repos/:owner/:repo/issues/:issue_number/labels
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getByOwnerAndRepoAndIssue_number(
  connection: IConnection<getByOwnerAndRepoAndIssue_number.Headers>,
  owner: string,
  repo: string,
  issue_number: string,
): Promise<getByOwnerAndRepoAndIssue_number.Output> {
  return !!connection.simulate
    ? getByOwnerAndRepoAndIssue_number.simulate(
        connection,
        owner,
        repo,
        issue_number,
      )
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getByOwnerAndRepoAndIssue_number.METADATA,
          path: getByOwnerAndRepoAndIssue_number.path(
            owner,
            repo,
            issue_number,
          ),
          status: null,
        },
      );
}
export namespace getByOwnerAndRepoAndIssue_number {
  export type Headers = IApiReposIssuesLabels.GetHeader;
  export type Output = label[];

  export const METADATA = {
    method: "GET",
    path: "/repos/:owner/:repo/issues/:issue_number/labels",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (owner: string, repo: string, issue_number: string) =>
    `/repos/${encodeURIComponent(owner ?? "null")}/${encodeURIComponent(repo ?? "null")}/issues/${encodeURIComponent(issue_number ?? "null")}/labels`;
  export const random = (g?: Partial<typia.IRandomGenerator>): label[] =>
    typia.random<label[]>(g);
  export const simulate = (
    connection: IConnection<getByOwnerAndRepoAndIssue_number.Headers>,
    owner: string,
    repo: string,
    issue_number: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: getByOwnerAndRepoAndIssue_number.path(owner, repo, issue_number),
      contentType: "application/json",
    });
    try {
      assert.param("owner")(() => typia.assert(owner));
      assert.param("repo")(() => typia.assert(repo));
      assert.param("issue_number")(() => typia.assert(issue_number));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
/**
 * Add labels to an issue.
 * Adds labels to an issue. If you provide an empty array of labels, all labels are removed from the issue.
 *
 * @tag issues
 * @path repos/:owner/:repo/issues/:issue_number/labels
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function postByOwnerAndRepoAndIssue_number(
  connection: IConnection<postByOwnerAndRepoAndIssue_number.Headers>,
  owner: string,
  repo: string,
  issue_number: string,
  body: postByOwnerAndRepoAndIssue_number.Input,
): Promise<postByOwnerAndRepoAndIssue_number.Output> {
  return !!connection.simulate
    ? postByOwnerAndRepoAndIssue_number.simulate(
        connection,
        owner,
        repo,
        issue_number,
        body,
      )
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...postByOwnerAndRepoAndIssue_number.METADATA,
          path: postByOwnerAndRepoAndIssue_number.path(
            owner,
            repo,
            issue_number,
          ),
          status: null,
        },
        body,
      );
}
export namespace postByOwnerAndRepoAndIssue_number {
  export type Headers = IApiReposIssuesLabels.PostHeader;
  export type Input = body;
  export type Output = label[];

  export const METADATA = {
    method: "POST",
    path: "/repos/:owner/:repo/issues/:issue_number/labels",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (owner: string, repo: string, issue_number: string) =>
    `/repos/${encodeURIComponent(owner ?? "null")}/${encodeURIComponent(repo ?? "null")}/issues/${encodeURIComponent(issue_number ?? "null")}/labels`;
  export const random = (g?: Partial<typia.IRandomGenerator>): label[] =>
    typia.random<label[]>(g);
  export const simulate = (
    connection: IConnection<postByOwnerAndRepoAndIssue_number.Headers>,
    owner: string,
    repo: string,
    issue_number: string,
    body: postByOwnerAndRepoAndIssue_number.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: postByOwnerAndRepoAndIssue_number.path(owner, repo, issue_number),
      contentType: "application/json",
    });
    try {
      assert.param("owner")(() => typia.assert(owner));
      assert.param("repo")(() => typia.assert(repo));
      assert.param("issue_number")(() => typia.assert(issue_number));
      assert.body(() => typia.assert(body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
/**
 * Set labels for an issue.
 * Removes any previous labels and sets the new labels for an issue.
 *
 * @tag issues
 * @path repos/:owner/:repo/issues/:issue_number/labels
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function putByOwnerAndRepoAndIssue_number(
  connection: IConnection<putByOwnerAndRepoAndIssue_number.Headers>,
  owner: string,
  repo: string,
  issue_number: string,
  body: putByOwnerAndRepoAndIssue_number.Input,
): Promise<putByOwnerAndRepoAndIssue_number.Output> {
  return !!connection.simulate
    ? putByOwnerAndRepoAndIssue_number.simulate(
        connection,
        owner,
        repo,
        issue_number,
        body,
      )
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...putByOwnerAndRepoAndIssue_number.METADATA,
          path: putByOwnerAndRepoAndIssue_number.path(
            owner,
            repo,
            issue_number,
          ),
          status: null,
        },
        body,
      );
}
export namespace putByOwnerAndRepoAndIssue_number {
  export type Headers = IApiReposIssuesLabels.PutHeader;
  export type Input = body;
  export type Output = label[];

  export const METADATA = {
    method: "PUT",
    path: "/repos/:owner/:repo/issues/:issue_number/labels",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (owner: string, repo: string, issue_number: string) =>
    `/repos/${encodeURIComponent(owner ?? "null")}/${encodeURIComponent(repo ?? "null")}/issues/${encodeURIComponent(issue_number ?? "null")}/labels`;
  export const random = (g?: Partial<typia.IRandomGenerator>): label[] =>
    typia.random<label[]>(g);
  export const simulate = (
    connection: IConnection<putByOwnerAndRepoAndIssue_number.Headers>,
    owner: string,
    repo: string,
    issue_number: string,
    body: putByOwnerAndRepoAndIssue_number.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: putByOwnerAndRepoAndIssue_number.path(owner, repo, issue_number),
      contentType: "application/json",
    });
    try {
      assert.param("owner")(() => typia.assert(owner));
      assert.param("repo")(() => typia.assert(repo));
      assert.param("issue_number")(() => typia.assert(issue_number));
      assert.body(() => typia.assert(body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
/**
 * Remove all labels from an issue.
 * Removes all labels from an issue.
 *
 * @tag issues
 * @path repos/:owner/:repo/issues/:issue_number/labels
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function eraseByOwnerAndRepoAndIssue_number(
  connection: IConnection<eraseByOwnerAndRepoAndIssue_number.Headers>,
  owner: string,
  repo: string,
  issue_number: string,
): Promise<void> {
  return !!connection.simulate
    ? eraseByOwnerAndRepoAndIssue_number.simulate(
        connection,
        owner,
        repo,
        issue_number,
      )
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...eraseByOwnerAndRepoAndIssue_number.METADATA,
          path: eraseByOwnerAndRepoAndIssue_number.path(
            owner,
            repo,
            issue_number,
          ),
          status: null,
        },
      );
}
export namespace eraseByOwnerAndRepoAndIssue_number {
  export type Headers = IApiReposIssuesLabels.DeleteHeader;

  export const METADATA = {
    method: "DELETE",
    path: "/repos/:owner/:repo/issues/:issue_number/labels",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (owner: string, repo: string, issue_number: string) =>
    `/repos/${encodeURIComponent(owner ?? "null")}/${encodeURIComponent(repo ?? "null")}/issues/${encodeURIComponent(issue_number ?? "null")}/labels`;
  export const random = (g?: Partial<typia.IRandomGenerator>): void =>
    typia.random<void>(g);
  export const simulate = (
    connection: IConnection<eraseByOwnerAndRepoAndIssue_number.Headers>,
    owner: string,
    repo: string,
    issue_number: string,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: eraseByOwnerAndRepoAndIssue_number.path(owner, repo, issue_number),
      contentType: "application/json",
    });
    try {
      assert.param("owner")(() => typia.assert(owner));
      assert.param("repo")(() => typia.assert(repo));
      assert.param("issue_number")(() => typia.assert(issue_number));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
/**
 * Remove a label from an issue.
 * Removes the specified label from the issue, and returns the remaining labels on the issue. This endpoint returns a `404 Not Found` status if the label does not exist.
 *
 * @tag issues
 * @path repos/:owner/:repo/issues/:issue_number/labels/:name
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function eraseByOwnerAndRepoAndIssue_numberAndName(
  connection: IConnection<eraseByOwnerAndRepoAndIssue_numberAndName.Headers>,
  owner: string,
  repo: string,
  issue_number: string,
  name: string,
): Promise<eraseByOwnerAndRepoAndIssue_numberAndName.Output> {
  return !!connection.simulate
    ? eraseByOwnerAndRepoAndIssue_numberAndName.simulate(
        connection,
        owner,
        repo,
        issue_number,
        name,
      )
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...eraseByOwnerAndRepoAndIssue_numberAndName.METADATA,
          path: eraseByOwnerAndRepoAndIssue_numberAndName.path(
            owner,
            repo,
            issue_number,
            name,
          ),
          status: null,
        },
      );
}
export namespace eraseByOwnerAndRepoAndIssue_numberAndName {
  export type Headers = IApiReposIssuesLabels.DeleteHeader;
  export type Output = label[];

  export const METADATA = {
    method: "DELETE",
    path: "/repos/:owner/:repo/issues/:issue_number/labels/:name",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (
    owner: string,
    repo: string,
    issue_number: string,
    name: string,
  ) =>
    `/repos/${encodeURIComponent(owner ?? "null")}/${encodeURIComponent(repo ?? "null")}/issues/${encodeURIComponent(issue_number ?? "null")}/labels/${encodeURIComponent(name ?? "null")}`;
  export const random = (g?: Partial<typia.IRandomGenerator>): label[] =>
    typia.random<label[]>(g);
  export const simulate = (
    connection: IConnection<eraseByOwnerAndRepoAndIssue_numberAndName.Headers>,
    owner: string,
    repo: string,
    issue_number: string,
    name: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: eraseByOwnerAndRepoAndIssue_numberAndName.path(
        owner,
        repo,
        issue_number,
        name,
      ),
      contentType: "application/json",
    });
    try {
      assert.param("owner")(() => typia.assert(owner));
      assert.param("repo")(() => typia.assert(repo));
      assert.param("issue_number")(() => typia.assert(issue_number));
      assert.param("name")(() => typia.assert(name));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
