import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IApiOrgsAttestations } from "../../../structures/IApiOrgsAttestations";
import { response } from "../../../structures/response";
/**
 * List attestations.
 * List a collection of artifact attestations with a given subject digest that are associated with repositories owned by an organization.
 *
 * The collection of attestations returned by this endpoint is filtered according to the authenticated user's permissions; if the authenticated user cannot read a repository, the attestations associated with that repository will not be included in the response. In addition, when using a fine-grained access token the `attestations:read` permission is required.
 *
 * **Please note:** in order to offer meaningful security benefits, an attestation's signature and timestamps **must** be cryptographically verified, and the identity of the attestation signer **must** be validated. Attestations can be verified using the [GitHub CLI `attestation verify` command](https://cli.github.com/manual/gh_attestation_verify). For more information, see [our guide on how to use artifact attestations to establish a build's provenance](https://docs.github.com/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds).
 *
 * @param subject_digest The parameter should be set to the attestation's subject's SHA256 digest, in the form `sha256:HEX_DIGEST`.
 * @tag orgs
 * @path orgs/:org/attestations/:subject_digest
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getByOrgAndSubject_digest(
  connection: IConnection<getByOrgAndSubject_digest.Headers>,
  org: string,
  subject_digest: string,
): Promise<getByOrgAndSubject_digest.Output> {
  return !!connection.simulate
    ? getByOrgAndSubject_digest.simulate(connection, org, subject_digest)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getByOrgAndSubject_digest.METADATA,
          path: getByOrgAndSubject_digest.path(org, subject_digest),
          status: null,
        },
      );
}
export namespace getByOrgAndSubject_digest {
  export type Headers = IApiOrgsAttestations.GetHeader;
  export type Output = response;

  export const METADATA = {
    method: "GET",
    path: "/orgs/:org/attestations/:subject_digest",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (org: string, subject_digest: string) =>
    `/orgs/${encodeURIComponent(org ?? "null")}/attestations/${encodeURIComponent(subject_digest ?? "null")}`;
  export const random = (g?: Partial<typia.IRandomGenerator>): response =>
    typia.random<response>(g);
  export const simulate = (
    connection: IConnection<getByOrgAndSubject_digest.Headers>,
    org: string,
    subject_digest: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: getByOrgAndSubject_digest.path(org, subject_digest),
      contentType: "application/json",
    });
    try {
      assert.param("org")(() => typia.assert(org));
      assert.param("subject_digest")(() => typia.assert(subject_digest));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
