import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import { IApiReposActionsJobsRerun } from "../../../../../structures/IApiReposActionsJobsRerun";
import { body } from "../../../../../structures/body";
import { empty_minus_object } from "../../../../../structures/empty_minus_object";

/**
 * Re-run a job from a workflow run.
 * Re-run a job and its dependent jobs in a workflow run.
 *
 * OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint.
 *
 * @tag actions
 * @path repos/:owner/:repo/actions/jobs/:job_id/rerun
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function postByOwnerAndRepoAndJob_id(
  connection: IConnection<postByOwnerAndRepoAndJob_id.Headers>,
  owner: string,
  repo: string,
  job_id: string,
  body: postByOwnerAndRepoAndJob_id.Input,
): Promise<postByOwnerAndRepoAndJob_id.Output> {
  return !!connection.simulate
    ? postByOwnerAndRepoAndJob_id.simulate(
        connection,
        owner,
        repo,
        job_id,
        body,
      )
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...postByOwnerAndRepoAndJob_id.METADATA,
          path: postByOwnerAndRepoAndJob_id.path(owner, repo, job_id),
          status: null,
        },
        body,
      );
}
export namespace postByOwnerAndRepoAndJob_id {
  export type Headers = IApiReposActionsJobsRerun.PostHeader;
  export type Input = body;
  export type Output = empty_minus_object;

  export const METADATA = {
    method: "POST",
    path: "/repos/:owner/:repo/actions/jobs/:job_id/rerun",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (owner: string, repo: string, job_id: string) =>
    `/repos/${encodeURIComponent(owner ?? "null")}/${encodeURIComponent(repo ?? "null")}/actions/jobs/${encodeURIComponent(job_id ?? "null")}/rerun`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): empty_minus_object => typia.random<empty_minus_object>(g);
  export const simulate = (
    connection: IConnection<postByOwnerAndRepoAndJob_id.Headers>,
    owner: string,
    repo: string,
    job_id: string,
    body: postByOwnerAndRepoAndJob_id.Input,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: postByOwnerAndRepoAndJob_id.path(owner, repo, job_id),
      contentType: "application/json",
    });
    try {
      assert.param("owner")(() => typia.assert(owner));
      assert.param("repo")(() => typia.assert(repo));
      assert.param("job_id")(() => typia.assert(job_id));
      assert.body(() => typia.assert(body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
