import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import { IApiUserPackages } from "../../../structures/IApiUserPackages";
import { packages } from "../../../structures/package";

export * as restore from "./restore";
export * as versions from "./versions";
/**
 * List packages for the authenticated user's namespace.
 * Lists packages owned by the authenticated user within the user's namespace.
 *
 * OAuth app tokens and personal access tokens (classic) need the `read:packages` scope to use this endpoint. If the `package_type` belongs to a GitHub Packages registry that only supports repository-scoped permissions, the `repo` scope is also required. For the list of these registries, see "[About permissions for GitHub Packages](https://docs.github.com/packages/learn-github-packages/about-permissions-for-github-packages#permissions-for-repository-scoped-packages)."
 *
 * @tag packages
 * @path user/packages
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function get(
  connection: IConnection<get.Headers>,
  query: get.Query,
): Promise<get.Output> {
  return !!connection.simulate
    ? get.simulate(connection, query)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...get.METADATA,
          path: get.path(query),
          status: null,
        },
      );
}
export namespace get {
  export type Headers = IApiUserPackages.GetHeader;
  export type Query = IApiUserPackages.GetQuery;
  export type Output = packages[];

  export const METADATA = {
    method: "GET",
    path: "/user/packages",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (query: get.Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/user/packages";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
  export const random = (g?: Partial<typia.IRandomGenerator>): packages[] =>
    typia.random<packages[]>(g);
  export const simulate = (
    connection: IConnection<get.Headers>,
    query: get.Query,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: get.path(query),
      contentType: "application/json",
    });
    try {
      assert.query(() => typia.assert(query));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
/**
 * Get a package for the authenticated user.
 * Gets a specific package for a package owned by the authenticated user.
 *
 * OAuth app tokens and personal access tokens (classic) need the `read:packages` scope to use this endpoint. If the `package_type` belongs to a GitHub Packages registry that only supports repository-scoped permissions, the `repo` scope is also required. For the list of these registries, see "[About permissions for GitHub Packages](https://docs.github.com/packages/learn-github-packages/about-permissions-for-github-packages#permissions-for-repository-scoped-packages)."
 *
 * @tag packages
 * @path user/packages/:package_type/:package_name
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getByPackage_typeAndPackage_name(
  connection: IConnection<getByPackage_typeAndPackage_name.Headers>,
  package_type: string,
  package_name: string,
): Promise<getByPackage_typeAndPackage_name.Output> {
  return !!connection.simulate
    ? getByPackage_typeAndPackage_name.simulate(
        connection,
        package_type,
        package_name,
      )
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getByPackage_typeAndPackage_name.METADATA,
          path: getByPackage_typeAndPackage_name.path(
            package_type,
            package_name,
          ),
          status: null,
        },
      );
}
export namespace getByPackage_typeAndPackage_name {
  export type Headers = IApiUserPackages.GetHeader;
  export type Output = packages;

  export const METADATA = {
    method: "GET",
    path: "/user/packages/:package_type/:package_name",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (package_type: string, package_name: string) =>
    `/user/packages/${encodeURIComponent(package_type ?? "null")}/${encodeURIComponent(package_name ?? "null")}`;
  export const random = (g?: Partial<typia.IRandomGenerator>): packages =>
    typia.random<packages>(g);
  export const simulate = (
    connection: IConnection<getByPackage_typeAndPackage_name.Headers>,
    package_type: string,
    package_name: string,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: getByPackage_typeAndPackage_name.path(package_type, package_name),
      contentType: "application/json",
    });
    try {
      assert.param("package_type")(() => typia.assert(package_type));
      assert.param("package_name")(() => typia.assert(package_name));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
/**
 * Delete a package for the authenticated user.
 * Deletes a package owned by the authenticated user. You cannot delete a public package if any version of the package has more than 5,000 downloads. In this scenario, contact GitHub support for further assistance.
 *
 * OAuth app tokens and personal access tokens (classic) need the `read:packages` and `delete:packages` scopes to use this endpoint. If the `package_type` belongs to a GitHub Packages registry that only supports repository-scoped permissions, `repo` scope is also required. For the list these registries, see "[About permissions for GitHub Packages](https://docs.github.com/packages/learn-github-packages/about-permissions-for-github-packages#permissions-for-repository-scoped-packages)."
 *
 * @tag packages
 * @path user/packages/:package_type/:package_name
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function eraseByPackage_typeAndPackage_name(
  connection: IConnection<eraseByPackage_typeAndPackage_name.Headers>,
  package_type: string,
  package_name: string,
): Promise<void> {
  return !!connection.simulate
    ? eraseByPackage_typeAndPackage_name.simulate(
        connection,
        package_type,
        package_name,
      )
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...eraseByPackage_typeAndPackage_name.METADATA,
          path: eraseByPackage_typeAndPackage_name.path(
            package_type,
            package_name,
          ),
          status: null,
        },
      );
}
export namespace eraseByPackage_typeAndPackage_name {
  export type Headers = IApiUserPackages.DeleteHeader;

  export const METADATA = {
    method: "DELETE",
    path: "/user/packages/:package_type/:package_name",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (package_type: string, package_name: string) =>
    `/user/packages/${encodeURIComponent(package_type ?? "null")}/${encodeURIComponent(package_name ?? "null")}`;
  export const random = (g?: Partial<typia.IRandomGenerator>): void =>
    typia.random<void>(g);
  export const simulate = (
    connection: IConnection<eraseByPackage_typeAndPackage_name.Headers>,
    package_type: string,
    package_name: string,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: eraseByPackage_typeAndPackage_name.path(package_type, package_name),
      contentType: "application/json",
    });
    try {
      assert.param("package_type")(() => typia.assert(package_type));
      assert.param("package_name")(() => typia.assert(package_name));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
